In [77]:
# Importing packages
import pandas as pd
import re

In [78]:
# Importing dataset
raw = pd.read_csv('../data/raw/d1_results_raw.csv')
raw

,season,date,event,weight_class,result,result_type,score,opponent,opponent_id,opponent_school,wrestler,wrestler_id,wrestler_school
0,2014,03/08,EIWA Championships,125,W,DEC,5 - 4,Caleb Richardson,12113,Pennsylvania,Chris McGinley,12050,Boston U
1,2014,03/08,EIWA Championships,125,L,FALL,2:48,David Terao,12068,American,Chris McGinley,12050,Boston U
2,2014,02/08,Princeton - Boston U Dual,125,W,MD,12 - 0,Ryan Cash,12045,Princeton,Chris McGinley,12050,Boston U
3,2014,02/02,Boston U - Binghamton Dual,125,L,DEC,9 - 6,David White,21963,Binghamton,Chris McGinley,12050,Boston U
4,2014,01/25,Harvard - Boston U Dual,125,W,MD,15 - 5,Max Mejia,17866,Harvard,Chris McGinley,12050,Boston U
...,...,...,...,...,...,...,...,...,...,...,...,...,...
441141,2025,11/10,Journeymen Classic,285,L,MD,8 - 0,Zach Delsanter,78837,Pennsylvania,Tristen Hitchcock,84264,Army West Point
441142,2025,11/10,Journeymen Classic,285,L,TB-2,3 - 2,Charlie Tibbitts,78440,Binghamton,Tristen Hitchcock,84264,Army West Point
441143,2025,11/03,Princeton Open,285,W,DEC,7 - 2,Braden Ewing,93488,Brown,Tristen Hitchcock,84264,Army West Point
441144,2025,11/03,Princeton Open,285,L,DEC,4 - 1,Calvin Lachman,84428,Lehigh,Tristen Hitchcock,84264,Army West Point
441145,2025,11/03,Princeton Open,285,L,DEC,3 - 1,Sungyup Ryu,62737,Columbia,Tristen Hitchcock,84264,Army West Point

In [79]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 441146 entries, 0 to 441145
Data columns (total 13 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   season           441146 non-null  int64
 1   date             441146 non-null  object
 2   event            441146 non-null  object
 3   weight_class     441146 non-null  int64
 4   result           441146 non-null  object
 5   result_type      441146 non-null  object
 6   score            441146 non-null  object
 7   opponent         441146 non-null  object
 8   opponent_id      441146 non-null  int64
 9   opponent_school  441146 non-null  object
 10  wrestler         441146 non-null  object
 11  wrestler_id      441146 non-null  int64
 12  wrestler_school  441146 non-null  object
dtypes: int64(4), object(9)
memory usage: 43.8+ MB

In [80]:
# Checking for any duplicated matches
len(raw[raw.duplicated(keep=False)])

0

In [81]:
raw.describe(include='all')

,season,date,event,weight_class,result,result_type,score,opponent,opponent_id,opponent_school,wrestler,wrestler_id,wrestler_school
count,441146.000000,441146,441146,441146.000000,441146,441146,441146,441146,441146.000000,441146,441146,441146.000000,441146
unique,NaN,133,4359,NaN,2,17,6561,31160,NaN,618,10467,NaN,83
top,NaN,12/29,Southern Scuffle,NaN,W,DEC,0 - 0,Ethan Smith,NaN,Army West Point,Ethan Smith,NaN,Army West Point
freq,NaN,18659,13456,NaN,238396,215909,12529,234,NaN,6805,244,NaN,8099
mean,2019.642207,NaN,NaN,170.153920,NaN,NaN,NaN,NaN,47731.649066,NaN,NaN,46799.746934,NaN
std,3.409520,NaN,NaN,42.566997,NaN,NaN,NaN,NaN,22404.292870,NaN,NaN,22475.255672,NaN
min,2014.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,11454.000000,NaN,NaN,11454.000000,NaN
25%,2017.000000,NaN,NaN,141.000000,NaN,NaN,NaN,NaN,23497.000000,NaN,NaN,20598.000000,NaN
50%,2019.000000,NaN,NaN,157.000000,NaN,NaN,NaN,NaN,49257.000000,NaN,NaN,49187.000000,NaN
75%,2023.000000,NaN,NaN,184.000000,NaN,NaN,NaN,NaN,63713.000000,NaN,NaN,63032.000000,NaN
max,2025.000000,NaN,NaN,285.000000,NaN,NaN,NaN,NaN,101285.000000,NaN,NaN,100984.000000,NaN

In [82]:
raw['score']

0          5 - 4
1           2:48
2         12 - 0
3          9 - 6
4         15 - 5
           ...
441141     8 - 0
441142     3 - 2
441143     7 - 2
441144     4 - 1
441145     3 - 1
Name: score, Length: 441146, dtype: object

In [83]:
raw.weight_class.value_counts()

weight_class
149    50488
157    48748
141    48524
165    46851
174    44305
285    42001
133    41783
184    41154
197    39506
125    37782
6          2
0          2
Name: count, dtype: int64

In [84]:
raw[(raw['weight_class'] == 0) | (raw['weight_class'] == 6)]

,season,date,event,weight_class,result,result_type,score,opponent,opponent_id,opponent_school,wrestler,wrestler_id,wrestler_school
23157,2015,11/15,Arizona State - Binghamton University Dual,6,W,DEC,13 - 8,Dylan Caruana,11934,Binghamton,Dylan Caruana,23324,Arizona State
30633,2015,11/15,Arizona State - Binghamton University Dual,6,L,DEC,13 - 8,Dylan Caruana,23324,Arizona State,Dylan Caruana,11934,Binghamton
35557,2015,12/06,George Mason - Franklin & Marshall Dual,0,W,MD,12 - 0,Derek Dwyer,13121,George Mason,184 Anthony Mancini,23444,Franklin And Marshall
38367,2015,12/06,George Mason - Franklin & Marshall Dual,0,L,MD,12 - 0,184 Anthony Mancini,23444,Franklin & Marshall,Derek Dwyer,13121,George Mason

In [85]:
raw = raw[~((raw['weight_class'] == 0) | (raw['weight_class'] == 6))].copy()
len(raw)

441142

In [86]:
raw.weight_class.unique()

array([125, 133, 141, 149, 157, 165, 174, 184, 197, 285])

In [87]:
raw.result_type.unique()

array(['DEC', 'FALL', 'MD', 'SV-1', 'TF5', 'SV-2', 'TF4', 'MFOR', 'TB-2',
       'TB-1', 'DEF', 'INJ', 'DQ', 'TB-3', 'SV-3', 'FOR', 'CMFF'],
      dtype=object)

In [88]:
raw.loc[raw['score'] == '4:12', 'score'] = '16 - 0 4:12'
raw.loc[raw['score'] == '17 - 1 :42', 'score'] = '17 - 1 1:42'
raw.loc[raw['score'] == '15 - 0 :00', 'score'] = '15 - 0 7:00'

In [89]:
def parse_score(row):
    val = row['score']
    
    # Normalize spacing: "26 -10 6:40" → "26 - 10 6:40"
    val = re.sub(r'\s*-\s*', ' - ', val.strip())        # normalize dashes
    val = re.sub(r'\s+', ' ', val)                      # collapse multiple spaces

    # Case 1: score + time (e.g. '15 - 0 :42', '20 - 3 0:0')
    match = re.match(r'^(\d+)\s-\s(\d+)\s+(:?\d{1,2}:\d{1,2})$', val)
    if match:
        score = f"{match.group(1)} - {match.group(2)}"
        time = match.group(3)
        return pd.Series([score, time])
    
    # Case 2: only score (e.g., '7-5')
    match = re.match(r'^(\d+)\s*-\s*(\d+)$', val)
    if match:
        return pd.Series([f"{match.group(1)} - {match.group(2)}", None])
    
    # Case 3: only time (e.g., '2:04', ':42')
    if re.match(r'^:?\d{1,2}:\d{1,2}$', val):
        return pd.Series([row['result_type'], val])
    
    # Fallback
    return pd.Series([val, None])

# Apply the function
raw[['score', 'match_duration']] = raw.apply(parse_score, axis=1)

In [ ]:
# Creating match_duration column from the score column and adjusting for special cases
raw.loc[raw['result_type'].isin(['MD', 'DEC']), 'match_duration'] = '7:00'
raw.loc[raw['result_type'] == 'SV-1', 'match_duration'] = '9:00'
raw.loc[raw['result_type'] == 'TB-1', 'match_duration'] = '10:00'
raw.loc[raw['result_type'] == 'SV-2', 'match_duration'] = '11:00'
raw.loc[raw['result_type'] == 'TB-2', 'match_duration'] = '12:00'
raw.loc[raw['result_type'] == 'SV-3', 'match_duration'] = '13:00'
raw.loc[raw['result_type'] == 'TB-3', 'match_duration'] = '14:00'
raw.loc[raw['result_type'].isin(['MFOR', 'FOR', 'CMFF', 'DQ', 'INJ']), 'match_duration'] = '0:00'
raw['match_duration'].fillna('0:00', inplace=True)
raw

,season,date,event,weight_class,result,result_type,score,opponent,opponent_id,opponent_school,wrestler,wrestler_id,wrestler_school,match_duration
0,2014,03/08,EIWA Championships,125,W,DEC,5 - 4,Caleb Richardson,12113,Pennsylvania,Chris McGinley,12050,Boston U,7:00
1,2014,03/08,EIWA Championships,125,L,FALL,FALL,David Terao,12068,American,Chris McGinley,12050,Boston U,2:48
2,2014,02/08,Princeton - Boston U Dual,125,W,MD,12 - 0,Ryan Cash,12045,Princeton,Chris McGinley,12050,Boston U,7:00
3,2014,02/02,Boston U - Binghamton Dual,125,L,DEC,9 - 6,David White,21963,Binghamton,Chris McGinley,12050,Boston U,7:00
4,2014,01/25,Harvard - Boston U Dual,125,W,MD,15 - 5,Max Mejia,17866,Harvard,Chris McGinley,12050,Boston U,7:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441141,2025,11/10,Journeymen Classic,285,L,MD,8 - 0,Zach Delsanter,78837,Pennsylvania,Tristen Hitchcock,84264,Army West Point,7:00
441142,2025,11/10,Journeymen Classic,285,L,TB-2,3 - 2,Charlie Tibbitts,78440,Binghamton,Tristen Hitchcock,84264,Army West Point,12:00
441143,2025,11/03,Princeton Open,285,W,DEC,7 - 2,Braden Ewing,93488,Brown,Tristen Hitchcock,84264,Army West Point,7:00
441144,2025,11/03,Princeton Open,285,L,DEC,4 - 1,Calvin Lachman,84428,Lehigh,Tristen Hitchcock,84264,Army West Point,7:00
441145,2025,11/03,Princeton Open,285,L,DEC,3 - 1,Sungyup Ryu,62737,Columbia,Tristen Hitchcock,84264,Army West Point,7:00

In [91]:
raw.loc[raw['result_type'].str.contains('TF')]

,season,date,event,weight_class,result,result_type,score,opponent,opponent_id,opponent_school,wrestler,wrestler_id,wrestler_school,match_duration
25,2014,12/07,Davidson - Boston U Dual,133,W,TF5,15 - 0,Anthony Elias,15359,Davidson,Dane Harlowe,12042,Boston U,7:00
49,2014,12/06,Penn State - Boston U Dual,141,L,TF5,17 - 2,Zain Retherford,11781,Penn State,Peter Ishiguro,11976,Boston U,4:48
50,2014,11/24,Keystone Classic,141,L,TF5,25 - 10,Ethan Raley,11731,Indiana,Peter Ishiguro,11976,Boston U,7:00
67,2014,02/22,Boston U - Sacred Heart Dual,157,W,TF5,20 - 3,Casey Mitchell,15264,Sacred Heart,Nestor Taffur,13505,Boston U,7:00
70,2014,02/02,Boston U - Binghamton Dual,157,W,TF5,18 - 3,Colton Perry,14787,Binghamton,Nestor Taffur,13505,Boston U,7:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441092,2025,11/10,Journeymen Classic,285,L,TF5,15 - 0,Isaac Trumble,67131,NC State,Brady Colbert,78625,Army West Point,6:19
441107,2025,11/24,Black Knight Invite,285,W,TF5,15 - 0,Tristen Hitchcock,84264,Army West Point,Lucas Stoddard,78565,Army West Point,5:42
441120,2025,11/24,Black Knight Invite,285,L,TF5,19 - 4,Cole Mirasola,84383,Penn State,Sam Sorenson,79465,Army West Point,3:28
441138,2025,11/24,Black Knight Invite,285,L,TF5,15 - 0,Lucas Stoddard,78565,Army West Point,Tristen Hitchcock,84264,Army West Point,5:42
441140,2025,11/10,Journeymen Classic,285,W,TF5,20 - 4,Matt Walker,79720,Sacred Heart,Tristen Hitchcock,84264,Army West Point,2:07

In [92]:
raw

,season,date,event,weight_class,result,result_type,score,opponent,opponent_id,opponent_school,wrestler,wrestler_id,wrestler_school,match_duration
0,2014,03/08,EIWA Championships,125,W,DEC,5 - 4,Caleb Richardson,12113,Pennsylvania,Chris McGinley,12050,Boston U,7:00
1,2014,03/08,EIWA Championships,125,L,FALL,FALL,David Terao,12068,American,Chris McGinley,12050,Boston U,2:48
2,2014,02/08,Princeton - Boston U Dual,125,W,MD,12 - 0,Ryan Cash,12045,Princeton,Chris McGinley,12050,Boston U,7:00
3,2014,02/02,Boston U - Binghamton Dual,125,L,DEC,9 - 6,David White,21963,Binghamton,Chris McGinley,12050,Boston U,7:00
4,2014,01/25,Harvard - Boston U Dual,125,W,MD,15 - 5,Max Mejia,17866,Harvard,Chris McGinley,12050,Boston U,7:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441141,2025,11/10,Journeymen Classic,285,L,MD,8 - 0,Zach Delsanter,78837,Pennsylvania,Tristen Hitchcock,84264,Army West Point,7:00
441142,2025,11/10,Journeymen Classic,285,L,TB-2,3 - 2,Charlie Tibbitts,78440,Binghamton,Tristen Hitchcock,84264,Army West Point,12:00
441143,2025,11/03,Princeton Open,285,W,DEC,7 - 2,Braden Ewing,93488,Brown,Tristen Hitchcock,84264,Army West Point,7:00
441144,2025,11/03,Princeton Open,285,L,DEC,4 - 1,Calvin Lachman,84428,Lehigh,Tristen Hitchcock,84264,Army West Point,7:00
441145,2025,11/03,Princeton Open,285,L,DEC,3 - 1,Sungyup Ryu,62737,Columbia,Tristen Hitchcock,84264,Army West Point,7:00

In [93]:
# Adding datetime column that captures full date
raw['temp_date'] = pd.to_datetime(raw['season'].astype('str') + '/' + raw['date'], format='%Y/%m/%d')
    
# Extract month to identify which dates need adjustment
raw['month'] = raw['temp_date'].dt.month

# Adjust year for months that are typically in the previous calendar year
# Assuming August-December (months 8-12) belong to the previous calendar year
raw['datetime'] = raw.apply(lambda row: 
    row['temp_date'].replace(year=int(row['season']) - 1) 
    if row['month'] >= 8  # August through December
    else row['temp_date'], axis=1)

# Clean up temporary columns and move datetime column
raw = raw.drop(['temp_date', 'month', 'date'], axis=1)
datetime = raw.pop('datetime')
raw.insert(1, 'date', datetime)

In [94]:
# Sorting the data by date and wrestler ID
raw = raw.sort_values(['date', 'wrestler_id']).copy()
raw['date']

4176     2013-11-01
4046     2013-11-01
13916    2013-11-01
13811    2013-11-01
13837    2013-11-01
            ...
401721   2025-03-20
420769   2025-03-20
420770   2025-03-20
420771   2025-03-20
420772   2025-03-20
Name: date, Length: 441142, dtype: datetime64[ns]

In [95]:
# Editing Season column to reflect full span
raw['season'] = (raw['season'] - 1).astype('str') + '/' + raw['season'].astype('str')
raw['season']

4176      2013/2014
4046      2013/2014
13916     2013/2014
13811     2013/2014
13837     2013/2014
            ...
401721    2024/2025
420769    2024/2025
420770    2024/2025
420771    2024/2025
420772    2024/2025
Name: season, Length: 441142, dtype: object

In [96]:
raw = raw.reset_index(drop=True)
raw

,season,date,event,weight_class,result,result_type,score,opponent,opponent_id,opponent_school,wrestler,wrestler_id,wrestler_school,match_duration
0,2013/2014,2013-11-01,Missouri - North Dakota State Dual,165,L,DEC,6 - 1,Steven Monk,37120,North Dakota State,Jordan Gagliano,11477,Missouri,7:00
1,2013/2014,2013-11-01,Missouri - North Dakota State Dual,141,L,DEC,4 - 1,Justin LaValle,37157,North Dakota State,Trevor Jauch,11593,Missouri,7:00
2,2013/2014,2013-11-01,Oklahoma Gold Classic,125,W,DEC,12 - 6,Max Soria,12190,Buffalo,David Terao,12068,American,7:00
3,2013/2014,2013-11-01,Missouri - North Dakota State Dual,174,W,DEC,3 - 1,Michael England,20057,Missouri,Hayden Zillmer,12280,North Dakota State,7:00
4,2013/2014,2013-11-01,Missouri - North Dakota State Dual,184,L,DEC,5 - 2,Johnny Eblen,12537,Missouri,Kurtis Julson,12375,North Dakota State,7:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441137,2024/2025,2025-03-20,NCAA Championships,174,L,FALL,FALL,Levi Haines,72657,Penn State,Branson John,92961,Maryland,2:46
441138,2024/2025,2025-03-20,NCAA Championships,184,L,TF5,19 - 4,Donnell Washington,57738,Indiana,Eddie Neitenbach,92977,Wyoming,2:41
441139,2024/2025,2025-03-20,NCAA Championships,184,W,SV-1,9 - 6,Nick Fine,71734,Columbia,Eddie Neitenbach,92977,Wyoming,9:00
441140,2024/2025,2025-03-20,NCAA Championships,184,W,FALL,FALL,TJ McDonnell,79786,Oregon State,Eddie Neitenbach,92977,Wyoming,1:08
441141,2024/2025,2025-03-20,NCAA Championships,184,L,MD,10 - 0,Deanthony Parker,71644,Oklahoma,Eddie Neitenbach,92977,Wyoming,7:00

In [97]:
# Swapping scores for matches where the wrestler lost to ensure the score reflects the wrestlers's perspective
raw[['score1', 'score2']] = raw['score'].str.split(' - ', expand=True)
raw.loc[raw['result'] == 'L', 'score'] = raw.score2 + ' - ' + raw.score1
raw.drop(['score1', 'score2'], axis=1, inplace=True)
raw

,season,date,event,weight_class,result,result_type,score,opponent,opponent_id,opponent_school,wrestler,wrestler_id,wrestler_school,match_duration
0,2013/2014,2013-11-01,Missouri - North Dakota State Dual,165,L,DEC,1 - 6,Steven Monk,37120,North Dakota State,Jordan Gagliano,11477,Missouri,7:00
1,2013/2014,2013-11-01,Missouri - North Dakota State Dual,141,L,DEC,1 - 4,Justin LaValle,37157,North Dakota State,Trevor Jauch,11593,Missouri,7:00
2,2013/2014,2013-11-01,Oklahoma Gold Classic,125,W,DEC,12 - 6,Max Soria,12190,Buffalo,David Terao,12068,American,7:00
3,2013/2014,2013-11-01,Missouri - North Dakota State Dual,174,W,DEC,3 - 1,Michael England,20057,Missouri,Hayden Zillmer,12280,North Dakota State,7:00
4,2013/2014,2013-11-01,Missouri - North Dakota State Dual,184,L,DEC,2 - 5,Johnny Eblen,12537,Missouri,Kurtis Julson,12375,North Dakota State,7:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441137,2024/2025,2025-03-20,NCAA Championships,174,L,FALL,NaN,Levi Haines,72657,Penn State,Branson John,92961,Maryland,2:46
441138,2024/2025,2025-03-20,NCAA Championships,184,L,TF5,4 - 19,Donnell Washington,57738,Indiana,Eddie Neitenbach,92977,Wyoming,2:41
441139,2024/2025,2025-03-20,NCAA Championships,184,W,SV-1,9 - 6,Nick Fine,71734,Columbia,Eddie Neitenbach,92977,Wyoming,9:00
441140,2024/2025,2025-03-20,NCAA Championships,184,W,FALL,FALL,TJ McDonnell,79786,Oregon State,Eddie Neitenbach,92977,Wyoming,1:08
441141,2024/2025,2025-03-20,NCAA Championships,184,L,MD,0 - 10,Deanthony Parker,71644,Oklahoma,Eddie Neitenbach,92977,Wyoming,7:00

In [98]:
raw.loc[raw['result_type'].isin(['FALL', 'INJ', 'DEF']), 'score'] = raw['result_type']

In [99]:
raw

,season,date,event,weight_class,result,result_type,score,opponent,opponent_id,opponent_school,wrestler,wrestler_id,wrestler_school,match_duration
0,2013/2014,2013-11-01,Missouri - North Dakota State Dual,165,L,DEC,1 - 6,Steven Monk,37120,North Dakota State,Jordan Gagliano,11477,Missouri,7:00
1,2013/2014,2013-11-01,Missouri - North Dakota State Dual,141,L,DEC,1 - 4,Justin LaValle,37157,North Dakota State,Trevor Jauch,11593,Missouri,7:00
2,2013/2014,2013-11-01,Oklahoma Gold Classic,125,W,DEC,12 - 6,Max Soria,12190,Buffalo,David Terao,12068,American,7:00
3,2013/2014,2013-11-01,Missouri - North Dakota State Dual,174,W,DEC,3 - 1,Michael England,20057,Missouri,Hayden Zillmer,12280,North Dakota State,7:00
4,2013/2014,2013-11-01,Missouri - North Dakota State Dual,184,L,DEC,2 - 5,Johnny Eblen,12537,Missouri,Kurtis Julson,12375,North Dakota State,7:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441137,2024/2025,2025-03-20,NCAA Championships,174,L,FALL,FALL,Levi Haines,72657,Penn State,Branson John,92961,Maryland,2:46
441138,2024/2025,2025-03-20,NCAA Championships,184,L,TF5,4 - 19,Donnell Washington,57738,Indiana,Eddie Neitenbach,92977,Wyoming,2:41
441139,2024/2025,2025-03-20,NCAA Championships,184,W,SV-1,9 - 6,Nick Fine,71734,Columbia,Eddie Neitenbach,92977,Wyoming,9:00
441140,2024/2025,2025-03-20,NCAA Championships,184,W,FALL,FALL,TJ McDonnell,79786,Oregon State,Eddie Neitenbach,92977,Wyoming,1:08
441141,2024/2025,2025-03-20,NCAA Championships,184,L,MD,0 - 10,Deanthony Parker,71644,Oklahoma,Eddie Neitenbach,92977,Wyoming,7:00

In [100]:
raw[raw.result_type.isin(['SV-1', 'SV-2', 'SV-3', 'TB-1', 'TB-2', 'TB-3'])]

,season,date,event,weight_class,result,result_type,score,opponent,opponent_id,opponent_school,wrestler,wrestler_id,wrestler_school,match_duration
12,2013/2014,2013-11-01,Missouri - North Dakota State Dual,285,W,TB-2,4 - 3,Evan Knutson,14327,North Dakota State,Devin Mellon,14302,Missouri,12:00
13,2013/2014,2013-11-01,Missouri - North Dakota State Dual,285,L,TB-2,3 - 4,Devin Mellon,14302,Missouri,Evan Knutson,14327,North Dakota State,12:00
46,2013/2014,2013-11-02,Menlo (Calif) - Stanford Dual,165,W,SV-1,4 - 2,Eric Lopez,22355,Menlo,Jim Wilson,11535,Stanford,9:00
265,2013/2014,2013-11-02,Cowboy Open,197,W,SV-1,4 - 2,Robert Isley,14478,Air Force,Chace Eskam,13040,Arizona State,9:00
393,2013/2014,2013-11-02,Citadel Open,285,L,TB-2,5 - 5,Austin Akins,14275,Coker,Joe Bexley,14177,The Citadel,12:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441100,2024/2025,2025-03-20,NCAA Championships,133,W,SV-1,6 - 3,Blake Boarman,70737,Chattanooga,Tyler Knox,83265,Stanford,9:00
441102,2024/2025,2025-03-20,NCAA Championships,174,L,SV-1,1 - 4,Joshua Ogunsanya,66970,North Carolina,Myles Takats,83325,Bucknell,9:00
441120,2024/2025,2025-03-20,NCAA Championships,157,L,SV-1,7 - 10,Caleb Fish,63045,Oklahoma State,Brandon Cannon,84352,Ohio State,9:00
441125,2024/2025,2025-03-20,NCAA Championships,184,W,SV-1,4 - 1,Shane Cartagena-Walsh,81579,Rutgers,Aidan Brenot,84734,North Dakota State,9:00
441139,2024/2025,2025-03-20,NCAA Championships,184,W,SV-1,9 - 6,Nick Fine,71734,Columbia,Eddie Neitenbach,92977,Wyoming,9:00

In [101]:
len(raw)

441142

In [102]:
raw.describe(include='all')

,season,date,event,weight_class,result,result_type,score,opponent,opponent_id,opponent_school,wrestler,wrestler_id,wrestler_school,match_duration
count,441142,441142,441142,441142.000000,441142,441142,441142,441142,441142.000000,441142,441142,441142.000000,441142,441142
unique,12,NaN,4359,NaN,2,17,666,31159,NaN,618,10466,NaN,83,527
top,2016/2017,NaN,Southern Scuffle,NaN,W,DEC,FALL,Ethan Smith,NaN,Army West Point,Ethan Smith,NaN,Army West Point,7:00
freq,42693,NaN,13456,NaN,238394,215907,74249,234,NaN,6805,244,NaN,8099,306125
mean,NaN,2019-08-19 07:21:59.003857920,NaN,170.155435,NaN,NaN,NaN,NaN,47731.919056,NaN,NaN,46800.008473,NaN,NaN
min,NaN,2013-11-01 00:00:00,NaN,125.000000,NaN,NaN,NaN,NaN,11454.000000,NaN,NaN,11454.000000,NaN,NaN
25%,NaN,2016-11-19 00:00:00,NaN,141.000000,NaN,NaN,NaN,NaN,23501.250000,NaN,NaN,20598.000000,NaN,NaN
50%,NaN,2019-02-16 00:00:00,NaN,157.000000,NaN,NaN,NaN,NaN,49257.000000,NaN,NaN,49187.000000,NaN,NaN
75%,NaN,2022-11-20 00:00:00,NaN,184.000000,NaN,NaN,NaN,NaN,63713.000000,NaN,NaN,63032.000000,NaN,NaN
max,NaN,2025-03-20 00:00:00,NaN,285.000000,NaN,NaN,NaN,NaN,101285.000000,NaN,NaN,100984.000000,NaN,NaN
std,NaN,NaN,NaN,42.564213,NaN,NaN,NaN,NaN,22404.209032,NaN,NaN,22475.183761,NaN,NaN

In [103]:
raw

,season,date,event,weight_class,result,result_type,score,opponent,opponent_id,opponent_school,wrestler,wrestler_id,wrestler_school,match_duration
0,2013/2014,2013-11-01,Missouri - North Dakota State Dual,165,L,DEC,1 - 6,Steven Monk,37120,North Dakota State,Jordan Gagliano,11477,Missouri,7:00
1,2013/2014,2013-11-01,Missouri - North Dakota State Dual,141,L,DEC,1 - 4,Justin LaValle,37157,North Dakota State,Trevor Jauch,11593,Missouri,7:00
2,2013/2014,2013-11-01,Oklahoma Gold Classic,125,W,DEC,12 - 6,Max Soria,12190,Buffalo,David Terao,12068,American,7:00
3,2013/2014,2013-11-01,Missouri - North Dakota State Dual,174,W,DEC,3 - 1,Michael England,20057,Missouri,Hayden Zillmer,12280,North Dakota State,7:00
4,2013/2014,2013-11-01,Missouri - North Dakota State Dual,184,L,DEC,2 - 5,Johnny Eblen,12537,Missouri,Kurtis Julson,12375,North Dakota State,7:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441137,2024/2025,2025-03-20,NCAA Championships,174,L,FALL,FALL,Levi Haines,72657,Penn State,Branson John,92961,Maryland,2:46
441138,2024/2025,2025-03-20,NCAA Championships,184,L,TF5,4 - 19,Donnell Washington,57738,Indiana,Eddie Neitenbach,92977,Wyoming,2:41
441139,2024/2025,2025-03-20,NCAA Championships,184,W,SV-1,9 - 6,Nick Fine,71734,Columbia,Eddie Neitenbach,92977,Wyoming,9:00
441140,2024/2025,2025-03-20,NCAA Championships,184,W,FALL,FALL,TJ McDonnell,79786,Oregon State,Eddie Neitenbach,92977,Wyoming,1:08
441141,2024/2025,2025-03-20,NCAA Championships,184,L,MD,0 - 10,Deanthony Parker,71644,Oklahoma,Eddie Neitenbach,92977,Wyoming,7:00

In [104]:
raw = raw.iloc[:, [0, 1, 2, 3, 10, 11, 12, 7, 8, 9, 4, 5, 6, 13]].copy()
raw

,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,opponent_school,result,result_type,score,match_duration
0,2013/2014,2013-11-01,Missouri - North Dakota State Dual,165,Jordan Gagliano,11477,Missouri,Steven Monk,37120,North Dakota State,L,DEC,1 - 6,7:00
1,2013/2014,2013-11-01,Missouri - North Dakota State Dual,141,Trevor Jauch,11593,Missouri,Justin LaValle,37157,North Dakota State,L,DEC,1 - 4,7:00
2,2013/2014,2013-11-01,Oklahoma Gold Classic,125,David Terao,12068,American,Max Soria,12190,Buffalo,W,DEC,12 - 6,7:00
3,2013/2014,2013-11-01,Missouri - North Dakota State Dual,174,Hayden Zillmer,12280,North Dakota State,Michael England,20057,Missouri,W,DEC,3 - 1,7:00
4,2013/2014,2013-11-01,Missouri - North Dakota State Dual,184,Kurtis Julson,12375,North Dakota State,Johnny Eblen,12537,Missouri,L,DEC,2 - 5,7:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441137,2024/2025,2025-03-20,NCAA Championships,174,Branson John,92961,Maryland,Levi Haines,72657,Penn State,L,FALL,FALL,2:46
441138,2024/2025,2025-03-20,NCAA Championships,184,Eddie Neitenbach,92977,Wyoming,Donnell Washington,57738,Indiana,L,TF5,4 - 19,2:41
441139,2024/2025,2025-03-20,NCAA Championships,184,Eddie Neitenbach,92977,Wyoming,Nick Fine,71734,Columbia,W,SV-1,9 - 6,9:00
441140,2024/2025,2025-03-20,NCAA Championships,184,Eddie Neitenbach,92977,Wyoming,TJ McDonnell,79786,Oregon State,W,FALL,FALL,1:08
441141,2024/2025,2025-03-20,NCAA Championships,184,Eddie Neitenbach,92977,Wyoming,Deanthony Parker,71644,Oklahoma,L,MD,0 - 10,7:00

In [105]:
raw.score.unique()

array(['1 - 6', '1 - 4', '12 - 6', '3 - 1', '2 - 5', '5 - 2', '14 - 4',
       '3 - 9', '2 - 4', '2 - 10', '6 - 1', '4 - 3', '3 - 4', '4 - 14',
       '1 - 3', '4 - 1', '0 - 0', '4 - 2', '10 - 2', 'FALL', '10 - 1',
       '12 - 5', '7 - 11', '17 - 6', '17 - 2', 'DEF', '16 - 5', '8 - 5',
       '10 - 4', '10 - 0', '2 - 3', '4 - 6', '3 - 2', '12 - 3', '20 - 7',
       '16 - 6', '9 - 3', '12 - 7', '8 - 1', '15 - 0', '19 - 3', '16 - 1',
       '12 - 2', '8 - 0', '6 - 8', '3 - 5', '7 - 18', '7 - 2', '0 - 9',
       '14 - 10', '7 - 5', '0 - 3', '8 - 2', '15 - 6', '16 - 0', '9 - 0',
       '21 - 5', '10 - 14', '7 - 4', '14 - 3', '4 - 7', '14 - 0', '1 - 5',
       '1 - 16', '12 - 1', '0 - 15', '5 - 11', '11 - 1', '6 - 12',
       '6 - 2', '14 - 5', '2 - 12', '13 - 2', '19 - 6', '19 - 4', '7 - 3',
       '6 - 0', '18 - 2', '17 - 1', '9 - 1', '2 - 6', '5 - 0', '12 - 9',
       '10 - 5', '2 - 13', '4 - 18', '5 - 9', '7 - 0', '2 - 0', '18 - 3',
       '11 - 3', '5 - 4', '7 - 1', '9 - 4', '0 - 2', '0 - 1', '6 - 3',
       '5 - 3', '13 - 6', '13 - 9', '13 - 4', '5 - 1', '1 - 2', '1 - 7',
       '10 - 8', '8 - 4', '15 - 5', '5 - 15', '8 - 10', '5 - 7', '4 - 0',
       '9 - 2', '0 - 5', '3 - 6', '4 - 10', '7 - 12', '6 - 7', '15 - 4',
       '1 - 0', '11 - 4', '6 - 4', '0 - 7', '4 - 5', '9 - 5', '14 - 2',
       '4 - 11', '0 - 6', '12 - 0', '16 - 3', '5 - 8', '2 - 18', '11 - 2',
       '13 - 0', '15 - 1', '14 - 6', '6 - 5', '2 - 1', '10 - 12', '5 - 6',
       '17 - 5', '10 - 3', '10 - 11', '4 - 13', '5 - 14', '0 - 10',
       '7 - 8', '7 - 9', '13 - 5', '3 - 7', '3 - 8', '8 - 3', '4 - 8',
       '5 - 5', '3 - 13', '3 - 0', '9 - 8', '7 - 6', '1 - 8', '1 - 10',
       '6 - 9', '11 - 0', '11 - 7', '3 - 19', '1 - 17', '6 - 10',
       '3 - 11', '12 - 4', '6 - 17', '0 - 8', '9 - 12', '9 - 6', '4 - 15',
       '13 - 7', '4 - 12', '10 - 6', '15 - 2', '13 - 11', '5 - 10',
       '19 - 5', '7 - 16', '11 - 10', '7 - 13', '6 - 6', '8 - 6',
       '0 - 12', '3 - 17', '5 - 12', '4 - 9', '7 - 10', '2 - 11',
       '8 - 18', '12 - 14', '0 - 13', '9 - 7', '0 - 16', '1 - 11',
       '14 - 1', '8 - 7', '13 - 3', '3 - 10', '21 - 4', '1 - 14',
       '5 - 16', '16 - 7', '20 - 4', '1 - 13', '3 - 15', '2 - 9',
       '4 - 19', '12 - 13', '11 - 13', '2 - 7', '1 - 9', '2 - 8',
       '15 - 10', '2 - 17', '2 - 14', '6 - 15', '18 - 6', '16 - 2',
       '17 - 0', '0 - 4', '21 - 6', '10 - 7', '24 - 8', '8 - 24',
       '4 - 17', '22 - 5', '12 - 10', '13 - 1', '3 - 14', '14 - 16',
       '14 - 9', '3 - 18', '1 - 18', '11 - 6', '18 - 1', '6 - 14',
       '9 - 14', '6 - 16', '17 - 4', '15 - 3', '6 - 11', '19 - 2',
       '23 - 8', '19 - 1', '18 - 7', '23 - 10', '19 - 8', '9 - 11',
       '18 - 8', '20 - 5', '11 - 12', '5 - 20', '12 - 11', '13 - 8',
       '0 - 11', '1 - 12', '8 - 13', '17 - 7', '7 - 17', '22 - 9',
       '9 - 13', '19 - 0', '9 - 22', '6 - 19', '5 - 17', '8 - 9',
       '6 - 13', '17 - 3', '10 - 9', '9 - 10', '20 - 9', '7 - 14',
       '11 - 5', '19 - 10', '19 - 9', '9 - 19', '18 - 5', '6 - 21',
       '5 - 13', '9 - 21', '4 - 16', '20 - 13', '2 - 15', '9 - 24',
       '2 - 19', '8 - 15', '3 - 20', '15 - 8', '11 - 14', '19 - 7',
       '14 - 11', '3 - 12', '16 - 4', '11 - 8', '21 - 9', '8 - 11',
       '14 - 8', '8 - 23', '0 - 19', '5 - 18', '14 - 12', '8 - 14', 'INJ',
       '8 - 19', '24 - 9', '20 - 3', '3 - 16', '20 - 2', '21 - 8',
       '25 - 10', '8 - 12', '7 - 19', '6 - 18', '12 - 8', '9 - 20',
       '0 - 17', '2 - 16', '26 - 11', '16 - 9', '9 - 16', '22 - 6',
       '5 - 21', '4 - 4', '15 - 21', '22 - 7', '11 - 9', '14 - 7',
       '7 - 22', '16 - 8', '21 - 15', '7 - 20', '20 - 8', '15 - 9',
       '5 - 22', '10 - 19', '8 - 16', '0 - 18', '9 - 15', '23 - 6',
       '23 - 4', '18 - 4', '15 - 7', '7 - 15', '1 - 19', '10 - 18',
       '18 - 10', '2 - 2', '4 - 21', '23 - 7', '7 - 23', '6 - 20',
       '10 - 25', '17 - 8', '8 - 17', '29 - 10', '8 - 20', '20 - 6',
       '16 - 13', '22 - 8', '25 - 12', '8 - 22', '12 - 25', '13 - 16',
       '18 - 0', '0 - 14', '3 - 3', '18 - 9', '9 - 18', '14 - 15',
       '5 - 19', '14 - 18', '19 - 11', '9 - 23', '11 - 19', '23 - 9',
       '6 - 22', '18 - 15', '15 - 18', '15 - 11', '11 - 15', '10 - 13',
       '13 - 10', '1 - 15', '11 - 26', '24 - 7', '9 - 17', '13 - 15',
       '15 - 13', '20 - 10', '10 - 20', '8 - 21', '14 - 24', '24 - 14',
       '10 - 15', '6 - 23', '15 - 17', '17 - 15', '4 - 20', '22 - 4',
       '4 - 22', '21 - 3', '17 - 12', '12 - 17', '16 - 12', '8 - 26',
       '12 - 16', '28 - 13', '13 - 28', '22 - 14', '17 - 14', '14 - 17',
       '21 - 7', '7 - 21', '17 - 10', '10 - 17', '18 - 11', '11 - 18',
       '13 - 19', '7 - 24', '19 - 13', '24 - 6', '18 - 12', '13 - 12',
       '27 - 12', '12 - 18', '12 - 12', '22 - 11', '25 - 11', '11 - 22',
       '17 - 9', '18 - 13', '13 - 18', '17 - 11', '11 - 17', '25 - 8',
       '13 - 14', '10 - 29', '20 - 12', '16 - 10', '10 - 16', '12 - 20',
       '3 - 23', '1 - 1', '3 - 21', '23 - 3', '29 - 13', '10 - 23',
       '14 - 13', '21 - 2', '21 - 10', '9 - 25', '19 - 17', '25 - 9',
       '10 - 21', '26 - 9', '9 - 26', '2 - 21', '15 - 12', '12 - 15',
       '12 - 22', '22 - 12', '20 - 1', '24 - 10', '10 - 24', '15 - 14',
       '15 - 20', '11 - 25', '29 - 14', '14 - 29', '16 - 11', '11 - 16',
       '27 - 11', '11 - 27', '12 - 27', '26 - 10', '10 - 26', '10 - 22',
       '22 - 10', '20 - 0', '0 - 20', '21 - 0', '23 - 5', '5 - 23',
       '24 - 5', '5 - 24', '21 - 14', '2 - 20', '23 - 12', '12 - 23',
       '1 - 20', '7 - 7', '6 - 24', '24 - 23', '23 - 24', '26 - 7',
       '19 - 23', '18 - 19', '15 - 16', '14 - 14', '16 - 15', '3 - 24',
       '26 - 12', '18 - 16', '25 - 4', '16 - 18', '24 - 3', '19 - 18',
       '4 - 25', '3 - 22', '22 - 3', '20 - 11', '27 - 7', '25 - 14',
       '11 - 20', '7 - 27', '20 - 16', '16 - 14', '26 - 8', '21 - 12',
       '14 - 27', '27 - 14', '15 - 19', '19 - 15', '11 - 11', '22 - 24',
       '8 - 25', '24 - 22', '0 - 21', '12 - 24', '17 - 18', '18 - 17',
       '21 - 11', '4 - 23', '31 - 17', '17 - 13', '13 - 17', '19 - 12',
       '14 - 23', '27 - 8', '8 - 27', '23 - 11', '11 - 23', '14 - 25',
       '18 - 14', '27 - 13', '20 - 14', '17 - 16', '16 - 17', '14 - 20',
       '29 - 11', '17 - 20', '21 - 1', '1 - 21', '26 - 6', '6 - 26',
       '30 - 14', '14 - 30', '25 - 6', '12 - 26', '27 - 15', '25 - 7',
       '7 - 25', '21 - 16', '16 - 21', '25 - 2', '2 - 25', '12 - 19',
       '22 - 2', '24 - 15', '15 - 24', '2 - 22', '28 - 12', '7 - 26',
       '5 - 25', '25 - 5', '16 - 19', '19 - 14', '19 - 16', '24 - 13',
       '13 - 24', '11 - 21', '12 - 21', '24 - 4', '25 - 13', '4 - 24',
       '13 - 25', '22 - 20', '26 - 14', '14 - 19', '24 - 12', '10 - 27',
       '27 - 10', '23 - 17', '1 - 22', '13 - 20', '37 - 39', '6 - 25',
       '39 - 37', '28 - 10', '17 - 22', '22 - 17', '22 - 13', '29 - 23',
       '13 - 22', '14 - 21', '23 - 21', '21 - 23', '13 - 21', '27 - 9',
       '21 - 13', '9 - 27', '20 - 15', '19 - 22', '21 - 27', '27 - 21',
       '16 - 31', '31 - 16', '30 - 13', '24 - 11', '13 - 30', '11 - 24',
       '32 - 16', '16 - 32', '30 - 15', '13 - 29', '28 - 6', '6 - 28',
       '23 - 15', '18 - 22', '22 - 0', '25 - 18', '18 - 25', '11 - 28',
       '28 - 11', '22 - 1', '20 - 22', '17 - 19', '15 - 23', '31 - 23',
       '23 - 31', '16 - 23', '23 - 13', '13 - 23', '23 - 2', '2 - 23',
       '31 - 11', '11 - 31', '24 - 20', '10 - 28', '14 - 28', '28 - 14',
       '12 - 29', '29 - 12', '20 - 17', '21 - 19', '23 - 1', '23 - 18',
       '25 - 27', '21 - 18', '15 - 22', '18 - 21', '22 - 15', '12 - 28',
       '25 - 19'], dtype=object)

In [106]:
# Adding unique match ID
def generate_match_id(row):
    import hashlib
    if ' - ' in str(row['score']):
        score1, score2 = row['score'].split(' - ')
        parts = [
            str(row["season"]),
            str(row["date"]),
            row["event"],
            str(row["weight_class"]),
            str(min(row["wrestler_id"], row["opponent_id"])),
            str(max(row["wrestler_id"], row["opponent_id"])),
            str(row["match_duration"]),
            str(min(int(score1), int(score2))), 
            str(max(int(score1), int(score2)))
        ]
    else:
        parts = [
            str(row["season"]),
            str(row["date"]),
            row["event"],
            str(row["weight_class"]),
            str(min(row["wrestler_id"], row["opponent_id"])),
            str(max(row["wrestler_id"], row["opponent_id"])),
            str(row["match_duration"]),
            str(row['score'])
        ]
    key = "_".join(parts).lower().replace(" ", "")
    return hashlib.md5(key.encode()).hexdigest()

In [107]:
raw['match_id'] = raw.apply(generate_match_id, axis=1)
len(raw)

441142

In [108]:
raw.drop_duplicates(subset='match_id', keep='first', inplace=True)
len(raw)

263412

In [109]:
raw[(raw.wrestler_id == 11477) & (raw.opponent_id == 37120)]

,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,opponent_school,result,result_type,score,match_duration,match_id
0,2013/2014,2013-11-01,Missouri - North Dakota State Dual,165,Jordan Gagliano,11477,Missouri,Steven Monk,37120,North Dakota State,L,DEC,1 - 6,7:00,b6570a52ea4818430421528a5bfabf3a

In [110]:
raw[(raw.opponent_id == 11477) & (raw.wrestler_id == 37120)]

Empty DataFrame
Columns: [season, date, event, weight_class, wrestler, wrestler_id, wrestler_school, opponent, opponent_id, opponent_school, result, result_type, score, match_duration, match_id]
Index: []

In [111]:
raw[~raw.result_type.isin(['DEC', 'MD'])]

,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,opponent_school,result,result_type,score,match_duration,match_id
12,2013/2014,2013-11-01,Missouri - North Dakota State Dual,285,Devin Mellon,14302,Missouri,Evan Knutson,14327,North Dakota State,W,TB-2,4 - 3,12:00,1321e1abc710e83c64aa00b779efbd7c
19,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Mike Soria,37251,Buffalo,Max Soria,12190,Buffalo,L,MFOR,0 - 0,0:00,0085fb59881f71ee03f25c0deaee2a7e
23,2013/2014,2013-11-02,Chicago - Northwestern Dual,174,Pierce Harger,11463,Northwestern,Steven Franke,23143,Chicago,W,FALL,FALL,6:47,d5ae05c249cd33a530967fcdf43f8d51
27,2013/2014,2013-11-02,Army - Franklin & Marshall Dual,165,Cole Gracey,11479,Army West Point,Rob King,14814,Franklin & Marshall,W,FALL,FALL,1:29,ced23c57c7019405913870a6977c9449
30,2013/2014,2013-11-02,West Virginia - Virginia Dual,165,Nick Sulzer,11483,Virginia,Jason Luster,13520,West Virginia,W,FALL,FALL,5:53,d7d31813e031cb1c6870884a07077eeb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440905,2024/2025,2025-03-20,NCAA Championships,125,Marcello Milani,78106,Cornell,Luke Lilledahl,80223,Penn State,L,TF5,4 - 19,4:25,caacd7d1e550c890bbf08a37f96470c4
440919,2024/2025,2025-03-20,NCAA Championships,165,Beau Mantanona,78420,Michigan,Cameron Steed,78549,Missouri,L,SV-1,1 - 4,9:00,c72376c5753101b6bfec385256209d8f
441045,2024/2025,2025-03-20,NCAA Championships,197,Remy Cotton,79392,Michigan State,Dillon Bechtold,84282,Bucknell,L,FALL,FALL,0:58,e3323726403cb41684ad46a867f76f35
441063,2024/2025,2025-03-20,NCAA Championships,184,TJ McDonnell,79786,Oregon State,Eddie Neitenbach,92977,Wyoming,L,FALL,FALL,1:08,2da99be54204a016311316f2bea09868
441083,2024/2025,2025-03-20,NCAA Championships,184,Shane Cartagena-Walsh,81579,Rutgers,Aidan Brenot,84734,North Dakota State,L,SV-1,1 - 4,9:00,13bb6aa28036590b933d2649219268cb

In [112]:
raw

,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,opponent_school,result,result_type,score,match_duration,match_id
0,2013/2014,2013-11-01,Missouri - North Dakota State Dual,165,Jordan Gagliano,11477,Missouri,Steven Monk,37120,North Dakota State,L,DEC,1 - 6,7:00,b6570a52ea4818430421528a5bfabf3a
1,2013/2014,2013-11-01,Missouri - North Dakota State Dual,141,Trevor Jauch,11593,Missouri,Justin LaValle,37157,North Dakota State,L,DEC,1 - 4,7:00,593514fa975e98adf63c218f85669272
2,2013/2014,2013-11-01,Oklahoma Gold Classic,125,David Terao,12068,American,Max Soria,12190,Buffalo,W,DEC,12 - 6,7:00,b54a0456288358b3b28cbebdce90cc66
3,2013/2014,2013-11-01,Missouri - North Dakota State Dual,174,Hayden Zillmer,12280,North Dakota State,Michael England,20057,Missouri,W,DEC,3 - 1,7:00,56b68d5970b5579a91f2b31877078808
4,2013/2014,2013-11-01,Missouri - North Dakota State Dual,184,Kurtis Julson,12375,North Dakota State,Johnny Eblen,12537,Missouri,L,DEC,2 - 5,7:00,44ed1cad3c5e45eddc9cc5c69c5431d5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441045,2024/2025,2025-03-20,NCAA Championships,197,Remy Cotton,79392,Michigan State,Dillon Bechtold,84282,Bucknell,L,FALL,FALL,0:58,e3323726403cb41684ad46a867f76f35
441048,2024/2025,2025-03-20,NCAA Championships,125,Caleb Weiand,79429,Michigan State,Gylon Sims,84440,The Citadel,W,DEC,8 - 4,7:00,f827141018be1786d3fb2846c75012ba
441058,2024/2025,2025-03-20,NCAA Championships,197,Camden McDanel,79473,Nebraska,Tucker Hogan,85083,Lock Haven,W,MD,13 - 2,7:00,ccaabc43aa6f027f596bc62ba29413c1
441063,2024/2025,2025-03-20,NCAA Championships,184,TJ McDonnell,79786,Oregon State,Eddie Neitenbach,92977,Wyoming,L,FALL,FALL,1:08,2da99be54204a016311316f2bea09868
441083,2024/2025,2025-03-20,NCAA Championships,184,Shane Cartagena-Walsh,81579,Rutgers,Aidan Brenot,84734,North Dakota State,L,SV-1,1 - 4,9:00,13bb6aa28036590b933d2649219268cb

In [113]:
raw[raw.match_duration.isna()]

Empty DataFrame
Columns: [season, date, event, weight_class, wrestler, wrestler_id, wrestler_school, opponent, opponent_id, opponent_school, result, result_type, score, match_duration, match_id]
Index: []

In [114]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
Index: 263412 entries, 0 to 441083
Data columns (total 15 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   season           263412 non-null  object
 1   date             263412 non-null  datetime64[ns]
 2   event            263412 non-null  object
 3   weight_class     263412 non-null  int64
 4   wrestler         263412 non-null  object
 5   wrestler_id      263412 non-null  int64
 6   wrestler_school  263412 non-null  object
 7   opponent         263412 non-null  object
 8   opponent_id      263412 non-null  int64
 9   opponent_school  263412 non-null  object
 10  result           263412 non-null  object
 11  result_type      263412 non-null  object
 12  score            263412 non-null  object
 13  match_duration   263412 non-null  object
 14  match_id         263412 non-null  object
dtypes: datetime64[ns](1), int64(3), object(11)
memory usage: 32.2+ MB