In [2]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from collections import defaultdict

In [4]:
raw = pd.read_csv('../data/clean/d1_results_unique.csv')
raw

,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,opponent_school,result,result_type,score,match_duration
0,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Mike Soria,37251,Buffalo,Max Soria,12190,Buffalo,L,MFOR,0 - 0,0:00
1,2013/2014,2013-11-01,Missouri - North Dakota State Dual,125,Hunter Weber,13273,North Dakota State,Barlow McGhee,13251,Missouri,L,DEC,2 - 5,7:00
2,2013/2014,2013-11-01,Oklahoma Gold Classic,125,David Terao,12068,American,Max Soria,12190,Buffalo,W,DEC,12 - 6,7:00
3,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Sean Boylan,37235,Bloomsburg,Max Soria,12190,Buffalo,L,DEC,2 - 4,7:00
4,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Hunter Wood,13327,Army West Point,Max Soria,12190,Buffalo,L,DEC,3 - 9,7:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263417,2024/2025,2025-03-20,NCAA Championships,285,Dayton Pitzer,72598,Pittsburgh,Daniel Bucknavich,62488,Cleveland State,W,DEC,6 - 2,7:00
263418,2024/2025,2025-03-20,NCAA Championships,285,Josh Heindselman,57311,Michigan,Isaac Trumble,67131,NC State,L,MD,0 - 9,7:00
263419,2024/2025,2025-03-20,NCAA Championships,285,Josh Heindselman,57311,Michigan,Brady Colbert,78625,Army West Point,W,TF,17 - 2,4:29
263420,2024/2025,2025-03-20,NCAA Championships,285,Wyatt Hendrickson,56694,Oklahoma State,Isaac Trumble,67131,NC State,W,FALL,FALL,2:15
263421,2024/2025,2025-03-20,NCAA Championships,285,Wyatt Hendrickson,56694,Oklahoma State,Max Vanadia,79307,Michigan State,W,FALL,FALL,1:18

In [5]:
raw[['score1', 'score2']] = raw['score'].str.split(' - ', expand=True)

raw['wrestler_score'] = np.where(raw['result'] == 'W', raw['score1'], 
                       np.where(raw['result'] == 'L', raw['score2'], 0))
raw['opponent_score'] = np.where(raw['result'] == 'W', raw['score2'], 
                       np.where(raw['result'] == 'L', raw['score1'], 0))

raw = raw.drop(['score1', 'score2'], axis=1)
raw

,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,opponent_school,result,result_type,score,match_duration,wrestler_score,opponent_score
0,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Mike Soria,37251,Buffalo,Max Soria,12190,Buffalo,L,MFOR,0 - 0,0:00,0,0
1,2013/2014,2013-11-01,Missouri - North Dakota State Dual,125,Hunter Weber,13273,North Dakota State,Barlow McGhee,13251,Missouri,L,DEC,2 - 5,7:00,5,2
2,2013/2014,2013-11-01,Oklahoma Gold Classic,125,David Terao,12068,American,Max Soria,12190,Buffalo,W,DEC,12 - 6,7:00,12,6
3,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Sean Boylan,37235,Bloomsburg,Max Soria,12190,Buffalo,L,DEC,2 - 4,7:00,4,2
4,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Hunter Wood,13327,Army West Point,Max Soria,12190,Buffalo,L,DEC,3 - 9,7:00,9,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263417,2024/2025,2025-03-20,NCAA Championships,285,Dayton Pitzer,72598,Pittsburgh,Daniel Bucknavich,62488,Cleveland State,W,DEC,6 - 2,7:00,6,2
263418,2024/2025,2025-03-20,NCAA Championships,285,Josh Heindselman,57311,Michigan,Isaac Trumble,67131,NC State,L,MD,0 - 9,7:00,9,0
263419,2024/2025,2025-03-20,NCAA Championships,285,Josh Heindselman,57311,Michigan,Brady Colbert,78625,Army West Point,W,TF,17 - 2,4:29,17,2
263420,2024/2025,2025-03-20,NCAA Championships,285,Wyatt Hendrickson,56694,Oklahoma State,Isaac Trumble,67131,NC State,W,FALL,FALL,2:15,FALL,None
263421,2024/2025,2025-03-20,NCAA Championships,285,Wyatt Hendrickson,56694,Oklahoma State,Max Vanadia,79307,Michigan State,W,FALL,FALL,1:18,FALL,None

In [6]:
raw['wrestler_score'] = np.where(raw['result_type'] != 'FALL', raw['wrestler_score'], 0)
raw['opponent_score'] = np.where(raw['result_type'] != 'FALL', raw['opponent_score'], 0)

In [7]:
raw = raw.drop(['score'], axis=1)
raw

,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,opponent_school,result,result_type,match_duration,wrestler_score,opponent_score
0,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Mike Soria,37251,Buffalo,Max Soria,12190,Buffalo,L,MFOR,0:00,0,0
1,2013/2014,2013-11-01,Missouri - North Dakota State Dual,125,Hunter Weber,13273,North Dakota State,Barlow McGhee,13251,Missouri,L,DEC,7:00,5,2
2,2013/2014,2013-11-01,Oklahoma Gold Classic,125,David Terao,12068,American,Max Soria,12190,Buffalo,W,DEC,7:00,12,6
3,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Sean Boylan,37235,Bloomsburg,Max Soria,12190,Buffalo,L,DEC,7:00,4,2
4,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Hunter Wood,13327,Army West Point,Max Soria,12190,Buffalo,L,DEC,7:00,9,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263417,2024/2025,2025-03-20,NCAA Championships,285,Dayton Pitzer,72598,Pittsburgh,Daniel Bucknavich,62488,Cleveland State,W,DEC,7:00,6,2
263418,2024/2025,2025-03-20,NCAA Championships,285,Josh Heindselman,57311,Michigan,Isaac Trumble,67131,NC State,L,MD,7:00,9,0
263419,2024/2025,2025-03-20,NCAA Championships,285,Josh Heindselman,57311,Michigan,Brady Colbert,78625,Army West Point,W,TF,4:29,17,2
263420,2024/2025,2025-03-20,NCAA Championships,285,Wyatt Hendrickson,56694,Oklahoma State,Isaac Trumble,67131,NC State,W,FALL,2:15,0,0
263421,2024/2025,2025-03-20,NCAA Championships,285,Wyatt Hendrickson,56694,Oklahoma State,Max Vanadia,79307,Michigan State,W,FALL,1:18,0,0

In [8]:
raw['is_dual_meet'] = [True if x == 'Dual' else False for x in raw['event']]

In [9]:
# Seems to be a decent number of matches with result types like 'MFOR', 'INJ', 'CMFF', 'DQ', 'DEF', and 'FOR'
print(len(raw))
print(len(raw[raw['result_type'].isin(['MFOR', 'INJ', 'CMFF', 'DQ', 'DEF', 'FOR'])]))

263422
10186

In [10]:
# Removing any matches that were not actually wrestled or were cut short (forfeit, injury, etc.)
raw = raw[~raw['result_type'].isin(['MFOR', 'INJ', 'CMFF', 'DQ', 'DEF', 'FOR'])]
len(raw)

253236

In [11]:
raw

,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,opponent_school,result,result_type,match_duration,wrestler_score,opponent_score,is_dual_meet
1,2013/2014,2013-11-01,Missouri - North Dakota State Dual,125,Hunter Weber,13273,North Dakota State,Barlow McGhee,13251,Missouri,L,DEC,7:00,5,2,False
2,2013/2014,2013-11-01,Oklahoma Gold Classic,125,David Terao,12068,American,Max Soria,12190,Buffalo,W,DEC,7:00,12,6,False
3,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Sean Boylan,37235,Bloomsburg,Max Soria,12190,Buffalo,L,DEC,7:00,4,2,False
4,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Hunter Wood,13327,Army West Point,Max Soria,12190,Buffalo,L,DEC,7:00,9,3,False
5,2013/2014,2013-11-01,Missouri - North Dakota State Dual,133,Eric Wilson,37466,Missouri,Justin Scherkenbach,13410,North Dakota State,W,DEC,7:00,4,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263417,2024/2025,2025-03-20,NCAA Championships,285,Dayton Pitzer,72598,Pittsburgh,Daniel Bucknavich,62488,Cleveland State,W,DEC,7:00,6,2,False
263418,2024/2025,2025-03-20,NCAA Championships,285,Josh Heindselman,57311,Michigan,Isaac Trumble,67131,NC State,L,MD,7:00,9,0,False
263419,2024/2025,2025-03-20,NCAA Championships,285,Josh Heindselman,57311,Michigan,Brady Colbert,78625,Army West Point,W,TF,4:29,17,2,False
263420,2024/2025,2025-03-20,NCAA Championships,285,Wyatt Hendrickson,56694,Oklahoma State,Isaac Trumble,67131,NC State,W,FALL,2:15,0,0,False
263421,2024/2025,2025-03-20,NCAA Championships,285,Wyatt Hendrickson,56694,Oklahoma State,Max Vanadia,79307,Michigan State,W,FALL,1:18,0,0,False