In [1]:
import pandas as pd
import numpy as np

In [2]:
raw = pd.read_csv('../data/clean/d1_results_unique.csv')
raw

,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,opponent_school,result,result_type,score,match_duration
0,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Mike Soria,37251,Buffalo,Max Soria,12190,Buffalo,L,MFOR,0 - 0,0:00
1,2013/2014,2013-11-01,Missouri - North Dakota State Dual,125,Hunter Weber,13273,North Dakota State,Barlow McGhee,13251,Missouri,L,DEC,2 - 5,7:00
2,2013/2014,2013-11-01,Oklahoma Gold Classic,125,David Terao,12068,American,Max Soria,12190,Buffalo,W,DEC,12 - 6,7:00
3,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Sean Boylan,37235,Bloomsburg,Max Soria,12190,Buffalo,L,DEC,2 - 4,7:00
4,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Hunter Wood,13327,Army West Point,Max Soria,12190,Buffalo,L,DEC,3 - 9,7:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263417,2024/2025,2025-03-20,NCAA Championships,285,Dayton Pitzer,72598,Pittsburgh,Daniel Bucknavich,62488,Cleveland State,W,DEC,6 - 2,7:00
263418,2024/2025,2025-03-20,NCAA Championships,285,Josh Heindselman,57311,Michigan,Isaac Trumble,67131,NC State,L,MD,0 - 9,7:00
263419,2024/2025,2025-03-20,NCAA Championships,285,Josh Heindselman,57311,Michigan,Brady Colbert,78625,Army West Point,W,TF,17 - 2,4:29
263420,2024/2025,2025-03-20,NCAA Championships,285,Wyatt Hendrickson,56694,Oklahoma State,Isaac Trumble,67131,NC State,W,FALL,FALL,2:15
263421,2024/2025,2025-03-20,NCAA Championships,285,Wyatt Hendrickson,56694,Oklahoma State,Max Vanadia,79307,Michigan State,W,FALL,FALL,1:18

In [3]:
raw[['wrestler_score', 'opponent_score']] = raw['score'].str.split(' - ', expand=True)
raw

,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,opponent_school,result,result_type,score,match_duration,wrestler_score,opponent_score
0,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Mike Soria,37251,Buffalo,Max Soria,12190,Buffalo,L,MFOR,0 - 0,0:00,0,0
1,2013/2014,2013-11-01,Missouri - North Dakota State Dual,125,Hunter Weber,13273,North Dakota State,Barlow McGhee,13251,Missouri,L,DEC,2 - 5,7:00,2,5
2,2013/2014,2013-11-01,Oklahoma Gold Classic,125,David Terao,12068,American,Max Soria,12190,Buffalo,W,DEC,12 - 6,7:00,12,6
3,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Sean Boylan,37235,Bloomsburg,Max Soria,12190,Buffalo,L,DEC,2 - 4,7:00,2,4
4,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Hunter Wood,13327,Army West Point,Max Soria,12190,Buffalo,L,DEC,3 - 9,7:00,3,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263417,2024/2025,2025-03-20,NCAA Championships,285,Dayton Pitzer,72598,Pittsburgh,Daniel Bucknavich,62488,Cleveland State,W,DEC,6 - 2,7:00,6,2
263418,2024/2025,2025-03-20,NCAA Championships,285,Josh Heindselman,57311,Michigan,Isaac Trumble,67131,NC State,L,MD,0 - 9,7:00,0,9
263419,2024/2025,2025-03-20,NCAA Championships,285,Josh Heindselman,57311,Michigan,Brady Colbert,78625,Army West Point,W,TF,17 - 2,4:29,17,2
263420,2024/2025,2025-03-20,NCAA Championships,285,Wyatt Hendrickson,56694,Oklahoma State,Isaac Trumble,67131,NC State,W,FALL,FALL,2:15,FALL,None
263421,2024/2025,2025-03-20,NCAA Championships,285,Wyatt Hendrickson,56694,Oklahoma State,Max Vanadia,79307,Michigan State,W,FALL,FALL,1:18,FALL,None

In [4]:
raw.loc[raw['result_type'] == 'FALL', ['wrestler_score', 'opponent_score']] = 0

In [5]:
raw

,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,opponent_school,result,result_type,score,match_duration,wrestler_score,opponent_score
0,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Mike Soria,37251,Buffalo,Max Soria,12190,Buffalo,L,MFOR,0 - 0,0:00,0,0
1,2013/2014,2013-11-01,Missouri - North Dakota State Dual,125,Hunter Weber,13273,North Dakota State,Barlow McGhee,13251,Missouri,L,DEC,2 - 5,7:00,2,5
2,2013/2014,2013-11-01,Oklahoma Gold Classic,125,David Terao,12068,American,Max Soria,12190,Buffalo,W,DEC,12 - 6,7:00,12,6
3,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Sean Boylan,37235,Bloomsburg,Max Soria,12190,Buffalo,L,DEC,2 - 4,7:00,2,4
4,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Hunter Wood,13327,Army West Point,Max Soria,12190,Buffalo,L,DEC,3 - 9,7:00,3,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263417,2024/2025,2025-03-20,NCAA Championships,285,Dayton Pitzer,72598,Pittsburgh,Daniel Bucknavich,62488,Cleveland State,W,DEC,6 - 2,7:00,6,2
263418,2024/2025,2025-03-20,NCAA Championships,285,Josh Heindselman,57311,Michigan,Isaac Trumble,67131,NC State,L,MD,0 - 9,7:00,0,9
263419,2024/2025,2025-03-20,NCAA Championships,285,Josh Heindselman,57311,Michigan,Brady Colbert,78625,Army West Point,W,TF,17 - 2,4:29,17,2
263420,2024/2025,2025-03-20,NCAA Championships,285,Wyatt Hendrickson,56694,Oklahoma State,Isaac Trumble,67131,NC State,W,FALL,FALL,2:15,0,0
263421,2024/2025,2025-03-20,NCAA Championships,285,Wyatt Hendrickson,56694,Oklahoma State,Max Vanadia,79307,Michigan State,W,FALL,FALL,1:18,0,0

In [6]:
raw = raw.drop(['score'], axis=1)
raw

,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,opponent_school,result,result_type,match_duration,wrestler_score,opponent_score
0,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Mike Soria,37251,Buffalo,Max Soria,12190,Buffalo,L,MFOR,0:00,0,0
1,2013/2014,2013-11-01,Missouri - North Dakota State Dual,125,Hunter Weber,13273,North Dakota State,Barlow McGhee,13251,Missouri,L,DEC,7:00,2,5
2,2013/2014,2013-11-01,Oklahoma Gold Classic,125,David Terao,12068,American,Max Soria,12190,Buffalo,W,DEC,7:00,12,6
3,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Sean Boylan,37235,Bloomsburg,Max Soria,12190,Buffalo,L,DEC,7:00,2,4
4,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Hunter Wood,13327,Army West Point,Max Soria,12190,Buffalo,L,DEC,7:00,3,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263417,2024/2025,2025-03-20,NCAA Championships,285,Dayton Pitzer,72598,Pittsburgh,Daniel Bucknavich,62488,Cleveland State,W,DEC,7:00,6,2
263418,2024/2025,2025-03-20,NCAA Championships,285,Josh Heindselman,57311,Michigan,Isaac Trumble,67131,NC State,L,MD,7:00,0,9
263419,2024/2025,2025-03-20,NCAA Championships,285,Josh Heindselman,57311,Michigan,Brady Colbert,78625,Army West Point,W,TF,4:29,17,2
263420,2024/2025,2025-03-20,NCAA Championships,285,Wyatt Hendrickson,56694,Oklahoma State,Isaac Trumble,67131,NC State,W,FALL,2:15,0,0
263421,2024/2025,2025-03-20,NCAA Championships,285,Wyatt Hendrickson,56694,Oklahoma State,Max Vanadia,79307,Michigan State,W,FALL,1:18,0,0

In [7]:
raw['is_dual_meet'] = [1 if x == 'Dual' else 0 for x in raw['event']]

In [8]:
# Seems to be a decent number of matches with result types like 'MFOR', 'INJ', 'CMFF', 'DQ', 'DEF', and 'FOR'
print(len(raw))
print(len(raw[raw['result_type'].isin(['MFOR', 'INJ', 'CMFF', 'DQ', 'DEF', 'FOR'])]))

263422
10186

In [9]:
# Removing any matches that were not actually wrestled or were cut short (forfeit, injury, etc.)
raw = raw[~raw['result_type'].isin(['MFOR', 'INJ', 'CMFF', 'DQ', 'DEF', 'FOR'])].copy()
len(raw)

253236

In [10]:
raw.result_type.value_counts()

result_type
DEC     124518
FALL     48476
MD       43509
TF       25326
SV-1      8537
TB-1      1431
TB-2       988
SV-2       318
TB-3        76
SV-3        57
Name: count, dtype: int64

In [11]:
def duration_to_seconds(duration_str):
    try:
        minutes, seconds = map(int, duration_str.split(":"))
        return minutes * 60 + seconds
    except:
        return None

# Convert to seconds
raw["duration_seconds"] = raw["match_duration"].apply(duration_to_seconds)

# Create is_overtime column (True if > 7 minutes)
raw["is_overtime"] = (raw["duration_seconds"] > 420).astype(int)

raw = raw.drop('match_duration', axis=1)

In [12]:
raw.columns

Index(['season', 'date', 'event', 'weight_class', 'wrestler', 'wrestler_id',
       'wrestler_school', 'opponent', 'opponent_id', 'opponent_school',
       'result', 'result_type', 'wrestler_score', 'opponent_score',
       'is_dual_meet', 'duration_seconds', 'is_overtime'],
      dtype='object')

In [13]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
Index: 253236 entries, 1 to 263421
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   season            253236 non-null  object
 1   date              253236 non-null  object
 2   event             253236 non-null  object
 3   weight_class      253236 non-null  int64
 4   wrestler          253236 non-null  object
 5   wrestler_id       253236 non-null  int64
 6   wrestler_school   253236 non-null  object
 7   opponent          253236 non-null  object
 8   opponent_id       253236 non-null  int64
 9   opponent_school   253236 non-null  object
 10  result            253236 non-null  object
 11  result_type       253236 non-null  object
 12  wrestler_score    253236 non-null  object
 13  opponent_score    253236 non-null  object
 14  is_dual_meet      253236 non-null  int64
 15  duration_seconds  253236 non-null  int64
 16  is_overtime       253236 non-null  int64
dtypes: int64(6), object(11)
memory usage: 34.8+ MB

In [14]:
raw['wrestler_score'] = pd.to_numeric(raw['wrestler_score'], errors='coerce')
raw['opponent_score'] = pd.to_numeric(raw['opponent_score'], errors='coerce')
raw.info()

<class 'pandas.core.frame.DataFrame'>
Index: 253236 entries, 1 to 263421
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   season            253236 non-null  object
 1   date              253236 non-null  object
 2   event             253236 non-null  object
 3   weight_class      253236 non-null  int64
 4   wrestler          253236 non-null  object
 5   wrestler_id       253236 non-null  int64
 6   wrestler_school   253236 non-null  object
 7   opponent          253236 non-null  object
 8   opponent_id       253236 non-null  int64
 9   opponent_school   253236 non-null  object
 10  result            253236 non-null  object
 11  result_type       253236 non-null  object
 12  wrestler_score    253236 non-null  int64
 13  opponent_score    253236 non-null  int64
 14  is_dual_meet      253236 non-null  int64
 15  duration_seconds  253236 non-null  int64
 16  is_overtime       253236 non-null  int64
dtypes: int64(8), object(9)
memory usage: 34.8+ MB

In [15]:
# Double matches so that each match has two rows (one from each wrestler perspective)
def double_matches(df):
    df_b = df.copy()
    df_b['wrestler_id'] = df['opponent_id']
    df_b['opponent_id'] = df['wrestler_id']
    df_b['wrestler'] = df['opponent']
    df_b['opponent'] = df['wrestler']
    df_b['wrestler_school'] = df['opponent_school']
    df_b['opponent_school'] = df['wrestler_school']
    df_b['wrestler_score'] = df['opponent_score']
    df_b['opponent_score'] = df['wrestler_score']
    df_b['result'] = np.where(df['result'] == 'W', 'L', 'W')

    result = pd.concat([df, df_b])
    return result.sort_values(['date', 'wrestler_id']).reset_index()
raw = double_matches(raw)

In [16]:
raw['is_win'] = (raw['result'] == 'W').astype(int)
raw['point_differential'] = raw['wrestler_score'] - raw['opponent_score']

In [17]:
raw

,index,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,opponent_school,result,result_type,wrestler_score,opponent_score,is_dual_meet,duration_seconds,is_overtime,is_win,point_differential
0,9,2013/2014,2013-11-01,Missouri - North Dakota State Dual,165,Jordan Gagliano,11477,Missouri,Steven Monk,37120,North Dakota State,L,DEC,1,6,0,420,0,0,-5
1,6,2013/2014,2013-11-01,Missouri - North Dakota State Dual,141,Trevor Jauch,11593,Missouri,Justin LaValle,37157,North Dakota State,L,DEC,1,4,0,420,0,0,-3
2,2,2013/2014,2013-11-01,Oklahoma Gold Classic,125,David Terao,12068,American,Max Soria,12190,Buffalo,W,DEC,12,6,0,420,0,1,6
3,2,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Max Soria,12190,Buffalo,David Terao,12068,American,L,DEC,6,12,0,420,0,0,-6
4,3,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Max Soria,12190,Buffalo,Sean Boylan,37235,Bloomsburg,W,DEC,4,2,0,420,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
506467,263167,2024/2025,2025-03-20,NCAA Championships,174,Branson John,92961,Maryland,Levi Haines,72657,Penn State,L,FALL,0,0,0,166,0,0,0
506468,263282,2024/2025,2025-03-20,NCAA Championships,184,Eddie Neitenbach,92977,Wyoming,Nick Fine,71734,Columbia,W,SV-1,9,6,0,540,1,1,3
506469,263283,2024/2025,2025-03-20,NCAA Championships,184,Eddie Neitenbach,92977,Wyoming,TJ McDonnell,79786,Oregon State,W,FALL,0,0,0,68,0,1,0
506470,263235,2024/2025,2025-03-20,NCAA Championships,184,Eddie Neitenbach,92977,Wyoming,Donnell Washington,57738,Indiana,L,TF,4,19,0,161,0,0,-15
506471,263281,2024/2025,2025-03-20,NCAA Championships,184,Eddie Neitenbach,92977,Wyoming,Deanthony Parker,71644,Oklahoma,L,MD,0,10,0,420,0,0,-10

In [18]:
raw = raw.sort_values(['date', 'wrestler_id']).copy()

In [19]:
raw

,index,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,opponent_school,result,result_type,wrestler_score,opponent_score,is_dual_meet,duration_seconds,is_overtime,is_win,point_differential
0,9,2013/2014,2013-11-01,Missouri - North Dakota State Dual,165,Jordan Gagliano,11477,Missouri,Steven Monk,37120,North Dakota State,L,DEC,1,6,0,420,0,0,-5
1,6,2013/2014,2013-11-01,Missouri - North Dakota State Dual,141,Trevor Jauch,11593,Missouri,Justin LaValle,37157,North Dakota State,L,DEC,1,4,0,420,0,0,-3
2,2,2013/2014,2013-11-01,Oklahoma Gold Classic,125,David Terao,12068,American,Max Soria,12190,Buffalo,W,DEC,12,6,0,420,0,1,6
3,2,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Max Soria,12190,Buffalo,David Terao,12068,American,L,DEC,6,12,0,420,0,0,-6
4,3,2013/2014,2013-11-01,Oklahoma Gold Classic,125,Max Soria,12190,Buffalo,Sean Boylan,37235,Bloomsburg,W,DEC,4,2,0,420,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
506467,263167,2024/2025,2025-03-20,NCAA Championships,174,Branson John,92961,Maryland,Levi Haines,72657,Penn State,L,FALL,0,0,0,166,0,0,0
506468,263282,2024/2025,2025-03-20,NCAA Championships,184,Eddie Neitenbach,92977,Wyoming,Nick Fine,71734,Columbia,W,SV-1,9,6,0,540,1,1,3
506469,263283,2024/2025,2025-03-20,NCAA Championships,184,Eddie Neitenbach,92977,Wyoming,TJ McDonnell,79786,Oregon State,W,FALL,0,0,0,68,0,1,0
506470,263235,2024/2025,2025-03-20,NCAA Championships,184,Eddie Neitenbach,92977,Wyoming,Donnell Washington,57738,Indiana,L,TF,4,19,0,161,0,0,-15
506471,263281,2024/2025,2025-03-20,NCAA Championships,184,Eddie Neitenbach,92977,Wyoming,Deanthony Parker,71644,Oklahoma,L,MD,0,10,0,420,0,0,-10

In [20]:
test = raw[raw['wrestler'] == 'Jacori Teemer'].tail(10)
test

,index,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,opponent_school,result,result_type,wrestler_score,opponent_score,is_dual_meet,duration_seconds,is_overtime,is_win,point_differential
494074,257061,2024/2025,2025-01-31,Iowa - Penn State Dual,157,Jacori Teemer,50581,Iowa,Tyler Kasak,78731,Penn State,L,DEC,2,5,0,420,0,0,-3
498818,259551,2024/2025,2025-02-14,Iowa - Minnesota Dual,157,Jacori Teemer,50581,Iowa,Tommy Askey,67040,Minnesota,W,DEC,4,1,0,420,0,1,3
501131,260937,2024/2025,2025-02-23,Oklahoma State - Iowa Dual,157,Jacori Teemer,50581,Iowa,Caleb Fish,63045,Oklahoma State,W,DEC,10,6,0,420,0,1,4
503768,262281,2024/2025,2025-03-08,Big Ten Championships,157,Jacori Teemer,50581,Iowa,Chase Saldate,61118,Michigan,W,DEC,8,3,0,420,0,1,5
503769,262282,2024/2025,2025-03-08,Big Ten Championships,157,Jacori Teemer,50581,Iowa,Luke Mechler,71940,Wisconsin,W,DEC,7,2,0,420,0,1,5
503770,262243,2024/2025,2025-03-08,Big Ten Championships,157,Jacori Teemer,50581,Iowa,Ethen Miller,70914,Maryland,L,SV-1,1,2,0,540,1,0,-1
503771,262259,2024/2025,2025-03-08,Big Ten Championships,157,Jacori Teemer,50581,Iowa,Jason Kraisser,57287,Illinois,W,MD,20,9,0,420,0,1,11
503772,262267,2024/2025,2025-03-08,Big Ten Championships,157,Jacori Teemer,50581,Iowa,Tommy Askey,67040,Minnesota,L,SV-1,1,4,0,540,1,0,-3
505200,263092,2024/2025,2025-03-20,NCAA Championships,157,Jacori Teemer,50581,Iowa,Johnny Lovett,61935,Central Michigan,L,MD,3,11,0,420,0,0,-8
505201,263073,2024/2025,2025-03-20,NCAA Championships,157,Jacori Teemer,50581,Iowa,Noah Castillo,67364,Chattanooga,L,DEC,5,8,0,420,0,0,-3

In [21]:
def calculate_win_rate_last_5(df):
    df = df.sort_values(['wrestler_id', 'date'])
    
    # Calculate rolling win rate for last 5 matches
    df['win_rate_last_5'] = df.groupby('wrestler_id')['is_win'].rolling(
        window=5, min_periods=1
    ).mean().reset_index(0, drop=True)
    
    # Shift by 1 to avoid data leakage (use data up to previous match)
    df['win_rate_last_5'] = df.groupby('wrestler_id')['win_rate_last_5'].shift(1)
    
    return df
test = calculate_win_rate_last_5(test)
test

,index,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,...,result,result_type,wrestler_score,opponent_score,is_dual_meet,duration_seconds,is_overtime,is_win,point_differential,win_rate_last_5
494074,257061,2024/2025,2025-01-31,Iowa - Penn State Dual,157,Jacori Teemer,50581,Iowa,Tyler Kasak,78731,...,L,DEC,2,5,0,420,0,0,-3,NaN
498818,259551,2024/2025,2025-02-14,Iowa - Minnesota Dual,157,Jacori Teemer,50581,Iowa,Tommy Askey,67040,...,W,DEC,4,1,0,420,0,1,3,0.000000
501131,260937,2024/2025,2025-02-23,Oklahoma State - Iowa Dual,157,Jacori Teemer,50581,Iowa,Caleb Fish,63045,...,W,DEC,10,6,0,420,0,1,4,0.500000
503768,262281,2024/2025,2025-03-08,Big Ten Championships,157,Jacori Teemer,50581,Iowa,Chase Saldate,61118,...,W,DEC,8,3,0,420,0,1,5,0.666667
503769,262282,2024/2025,2025-03-08,Big Ten Championships,157,Jacori Teemer,50581,Iowa,Luke Mechler,71940,...,W,DEC,7,2,0,420,0,1,5,0.750000
503770,262243,2024/2025,2025-03-08,Big Ten Championships,157,Jacori Teemer,50581,Iowa,Ethen Miller,70914,...,L,SV-1,1,2,0,540,1,0,-1,0.800000
503771,262259,2024/2025,2025-03-08,Big Ten Championships,157,Jacori Teemer,50581,Iowa,Jason Kraisser,57287,...,W,MD,20,9,0,420,0,1,11,0.800000
503772,262267,2024/2025,2025-03-08,Big Ten Championships,157,Jacori Teemer,50581,Iowa,Tommy Askey,67040,...,L,SV-1,1,4,0,540,1,0,-3,0.800000
505200,263092,2024/2025,2025-03-20,NCAA Championships,157,Jacori Teemer,50581,Iowa,Johnny Lovett,61935,...,L,MD,3,11,0,420,0,0,-8,0.600000
505201,263073,2024/2025,2025-03-20,NCAA Championships,157,Jacori Teemer,50581,Iowa,Noah Castillo,67364,...,L,DEC,5,8,0,420,0,0,-3,0.400000

In [22]:
def calculate_avg_point_differential_last_5(df):
    df = df.sort_values(['wrestler_id', 'date'])
    
    # Calculate rolling average point differential
    df['avg_point_differential_last_5'] = df.groupby('wrestler_id')['point_differential'].rolling(
        window=5, min_periods=1
    ).mean().reset_index(0, drop=True)
    
    # Shift to avoid data leakage
    df['avg_point_differential_last_5'] = df.groupby('wrestler_id')['avg_point_differential_last_5'].shift(1)
    
    return df
test = calculate_avg_point_differential_last_5(test)
test

,index,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,...,result_type,wrestler_score,opponent_score,is_dual_meet,duration_seconds,is_overtime,is_win,point_differential,win_rate_last_5,avg_point_differential_last_5
494074,257061,2024/2025,2025-01-31,Iowa - Penn State Dual,157,Jacori Teemer,50581,Iowa,Tyler Kasak,78731,...,DEC,2,5,0,420,0,0,-3,NaN,NaN
498818,259551,2024/2025,2025-02-14,Iowa - Minnesota Dual,157,Jacori Teemer,50581,Iowa,Tommy Askey,67040,...,DEC,4,1,0,420,0,1,3,0.000000,-3.000000
501131,260937,2024/2025,2025-02-23,Oklahoma State - Iowa Dual,157,Jacori Teemer,50581,Iowa,Caleb Fish,63045,...,DEC,10,6,0,420,0,1,4,0.500000,0.000000
503768,262281,2024/2025,2025-03-08,Big Ten Championships,157,Jacori Teemer,50581,Iowa,Chase Saldate,61118,...,DEC,8,3,0,420,0,1,5,0.666667,1.333333
503769,262282,2024/2025,2025-03-08,Big Ten Championships,157,Jacori Teemer,50581,Iowa,Luke Mechler,71940,...,DEC,7,2,0,420,0,1,5,0.750000,2.250000
503770,262243,2024/2025,2025-03-08,Big Ten Championships,157,Jacori Teemer,50581,Iowa,Ethen Miller,70914,...,SV-1,1,2,0,540,1,0,-1,0.800000,2.800000
503771,262259,2024/2025,2025-03-08,Big Ten Championships,157,Jacori Teemer,50581,Iowa,Jason Kraisser,57287,...,MD,20,9,0,420,0,1,11,0.800000,3.200000
503772,262267,2024/2025,2025-03-08,Big Ten Championships,157,Jacori Teemer,50581,Iowa,Tommy Askey,67040,...,SV-1,1,4,0,540,1,0,-3,0.800000,4.800000
505200,263092,2024/2025,2025-03-20,NCAA Championships,157,Jacori Teemer,50581,Iowa,Johnny Lovett,61935,...,MD,3,11,0,420,0,0,-8,0.600000,3.400000
505201,263073,2024/2025,2025-03-20,NCAA Championships,157,Jacori Teemer,50581,Iowa,Noah Castillo,67364,...,DEC,5,8,0,420,0,0,-3,0.400000,0.800000

In [23]:
test2 = raw[raw['date'] > '2019-12-01']
test2

,index,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,opponent_school,result,result_type,wrestler_score,opponent_score,is_dual_meet,duration_seconds,is_overtime,is_win,point_differential
283528,147214,2019/2020,2019-12-05,Pittsburgh - West Virginia Dual,197,Kellan Stout,39528,Pittsburgh,Noah Adams,49342,West Virginia,L,DEC,6,8,0,420,0,0,-2
283529,147211,2019/2020,2019-12-05,Bloomsburg - Bucknell Dual,184,Trevor Allard,40040,Bloomsburg,Kyle Inlander,44835,Bucknell,W,TF,18,3,0,420,0,1,15
283530,147206,2019/2020,2019-12-05,Pittsburgh - West Virginia Dual,157,Taleb Rahmani,40082,Pittsburgh,Alex Hornfeck,56494,West Virginia,W,DEC,7,6,0,420,0,1,1
283531,147215,2019/2020,2019-12-05,Bloomsburg - Bucknell Dual,285,Garrett Hoffman,44672,Bucknell,Jarrett Walters,50871,Bloomsburg,W,DEC,9,2,0,420,0,1,7
283532,147211,2019/2020,2019-12-05,Bloomsburg - Bucknell Dual,184,Kyle Inlander,44835,Bucknell,Trevor Allard,40040,Bloomsburg,L,TF,3,18,0,420,0,0,-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
506467,263167,2024/2025,2025-03-20,NCAA Championships,174,Branson John,92961,Maryland,Levi Haines,72657,Penn State,L,FALL,0,0,0,166,0,0,0
506468,263282,2024/2025,2025-03-20,NCAA Championships,184,Eddie Neitenbach,92977,Wyoming,Nick Fine,71734,Columbia,W,SV-1,9,6,0,540,1,1,3
506469,263283,2024/2025,2025-03-20,NCAA Championships,184,Eddie Neitenbach,92977,Wyoming,TJ McDonnell,79786,Oregon State,W,FALL,0,0,0,68,0,1,0
506470,263235,2024/2025,2025-03-20,NCAA Championships,184,Eddie Neitenbach,92977,Wyoming,Donnell Washington,57738,Indiana,L,TF,4,19,0,161,0,0,-15
506471,263281,2024/2025,2025-03-20,NCAA Championships,184,Eddie Neitenbach,92977,Wyoming,Deanthony Parker,71644,Oklahoma,L,MD,0,10,0,420,0,0,-10

In [24]:
test2[(test2['wrestler'] == 'Beau Bartlett') & (test2['opponent'] == 'Jesse Mendez')]

,index,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,opponent_school,result,result_type,wrestler_score,opponent_score,is_dual_meet,duration_seconds,is_overtime,is_win,point_differential
448847,233505,2023/2024,2024-02-02,Ohio State - Penn State Dual,141,Beau Bartlett,62221,Penn State,Jesse Mendez,74054,Ohio State,W,SV-1,4,1,0,540,1,1,3
457667,238053,2023/2024,2024-03-09,Big Ten Championships,141,Beau Bartlett,62221,Penn State,Jesse Mendez,74054,Ohio State,L,DEC,1,4,0,420,0,0,-3
459425,238868,2023/2024,2024-03-21,NCAA Championships,141,Beau Bartlett,62221,Penn State,Jesse Mendez,74054,Ohio State,L,DEC,1,4,0,420,0,0,-3
498858,259510,2024/2025,2025-02-14,Penn State - Ohio State Dual,141,Beau Bartlett,62221,Penn State,Jesse Mendez,74054,Ohio State,W,DEC,4,2,0,420,0,1,2
504006,262157,2024/2025,2025-03-08,Big Ten Championships,141,Beau Bartlett,62221,Penn State,Jesse Mendez,74054,Ohio State,W,DEC,4,2,0,420,0,1,2
505519,262947,2024/2025,2025-03-20,NCAA Championships,141,Beau Bartlett,62221,Penn State,Jesse Mendez,74054,Ohio State,L,TB-1,1,2,0,600,1,0,-1

In [25]:
def calculate_h2h_win_rate(df):
    df = df.sort_values(['wrestler_id', 'date'])
    
    # Create head-to-head combinations
    df['h2h_key'] = df.apply(lambda x: tuple(sorted([x['wrestler_id'], x['opponent_id']])), axis=1)
    
    # Calculate cumulative H2H record
    df['h2h_matches'] = df.groupby(['wrestler_id', 'opponent_id']).cumcount()
    df['h2h_wins'] = df.groupby(['wrestler_id', 'opponent_id'])['is_win'].cumsum()
    
    # Calculate H2H win rate (shift to avoid data leakage)
    df['h2h_win_rate'] = df['h2h_wins'] / (df['h2h_matches'] + 1)
    df['h2h_win_rate'] = df.groupby(['wrestler_id', 'opponent_id'])['h2h_win_rate'].shift(1)
    
    # Fill NaN with 0.5 (no previous history)
    df['h2h_win_rate'] = df['h2h_win_rate'].fillna(0.5)
    
    return df
test2 = calculate_h2h_win_rate(test2)
test2[(test2['wrestler'] == 'Beau Bartlett') & (test2['opponent'] == 'Jesse Mendez')]

,index,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,...,opponent_score,is_dual_meet,duration_seconds,is_overtime,is_win,point_differential,h2h_key,h2h_matches,h2h_wins,h2h_win_rate
448847,233505,2023/2024,2024-02-02,Ohio State - Penn State Dual,141,Beau Bartlett,62221,Penn State,Jesse Mendez,74054,...,1,0,540,1,1,3,"(62221, 74054)",0,1,0.500000
457667,238053,2023/2024,2024-03-09,Big Ten Championships,141,Beau Bartlett,62221,Penn State,Jesse Mendez,74054,...,4,0,420,0,0,-3,"(62221, 74054)",1,1,1.000000
459425,238868,2023/2024,2024-03-21,NCAA Championships,141,Beau Bartlett,62221,Penn State,Jesse Mendez,74054,...,4,0,420,0,0,-3,"(62221, 74054)",2,1,0.500000
498858,259510,2024/2025,2025-02-14,Penn State - Ohio State Dual,141,Beau Bartlett,62221,Penn State,Jesse Mendez,74054,...,2,0,420,0,1,2,"(62221, 74054)",3,2,0.333333
504006,262157,2024/2025,2025-03-08,Big Ten Championships,141,Beau Bartlett,62221,Penn State,Jesse Mendez,74054,...,2,0,420,0,1,2,"(62221, 74054)",4,3,0.500000
505519,262947,2024/2025,2025-03-20,NCAA Championships,141,Beau Bartlett,62221,Penn State,Jesse Mendez,74054,...,2,0,600,1,0,-1,"(62221, 74054)",5,3,0.600000

In [26]:
def calculate_opponent_career_win_rate(df):
    df = df.sort_values(['wrestler_id', 'date'])
    
    # Calculate cumulative win rate for each wrestler
    df['matches_wrestled'] = df.groupby('wrestler_id').cumcount() + 1
    df['cumulative_wins'] = df.groupby('wrestler_id')['is_win'].cumsum()
    df['career_win_rate'] = df['cumulative_wins'] / df['matches_wrestled']
    
    # Shift to get career win rate before current match
    df['career_win_rate'] = df.groupby('wrestler_id')['career_win_rate'].shift(1)
    
    # Create a mapping of wrestler career win rates by match date
    wrestler_rates = df.groupby(['wrestler_id', 'date'])['career_win_rate'].first().reset_index()
    
    # Map opponent win rates
    df = df.merge(
        wrestler_rates.rename(columns={'wrestler_id': 'opponent_id', 'career_win_rate': 'opponent_career_win_rate'}),
        on=['opponent_id', 'date'],
        how='left'
    )
    
    return df
test2 = calculate_opponent_career_win_rate(test2)
test2[(test2['wrestler'] == 'Beau Bartlett')].head(15)

,index,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,...,is_win,point_differential,h2h_key,h2h_matches,h2h_wins,h2h_win_rate,matches_wrestled,cumulative_wins,career_win_rate,opponent_career_win_rate
76609,164603,2020/2021,2021-01-30,Indiana Penn State Extra,141,Beau Bartlett,62221,Penn State,Jacob Moran,63550,...,1,0,"(62221, 63550)",0,1,0.5,1,1,NaN,1.000000
76610,164610,2020/2021,2021-01-30,Penn State Northwestern Extra,141,Beau Bartlett,62221,Penn State,Colin Valdiviez,49244,...,1,4,"(49244, 62221)",0,1,0.5,2,2,1.000000,0.666667
76611,164611,2020/2021,2021-01-30,Penn State Northwestern Extra,141,Beau Bartlett,62221,Penn State,Justin Benjamin,61997,...,1,6,"(61997, 62221)",0,1,0.5,3,3,1.000000,0.375000
76612,165191,2020/2021,2021-02-02,Penn State Wisconsin Extra,141,Beau Bartlett,62221,Penn State,Dominic Dentino,56924,...,1,7,"(56924, 62221)",0,1,0.5,4,4,1.000000,0.153846
76613,166398,2020/2021,2021-02-14,Michigan Penn State Extra,149,Beau Bartlett,62221,Penn State,Cole Mattin,57715,...,1,4,"(57715, 62221)",0,1,0.5,5,5,1.000000,0.500000
76614,166536,2020/2021,2021-02-19,Penn State - Ohio State Dual,149,Beau Bartlett,62221,Penn State,Sammy Sasso,51143,...,0,-2,"(51143, 62221)",0,0,0.5,6,5,1.000000,0.920000
76615,166673,2020/2021,2021-02-21,Maryland - Penn State Dual,149,Beau Bartlett,62221,Penn State,Hunter Baxter,49172,...,1,6,"(49172, 62221)",0,1,0.5,7,6,0.833333,0.115385
76616,166674,2020/2021,2021-02-21,Penn State Maryland Extra,149,Beau Bartlett,62221,Penn State,Lucas Cordio,57120,...,1,8,"(57120, 62221)",0,1,0.5,8,7,0.857143,0.421053
76617,167598,2020/2021,2021-03-06,Big Ten Championships,149,Beau Bartlett,62221,Penn State,Michael Blockhus,57163,...,0,-2,"(57163, 62221)",0,0,0.5,9,7,0.875000,0.628571
76618,167576,2020/2021,2021-03-06,Big Ten Championships,149,Beau Bartlett,62221,Penn State,Michael North,57335,...,1,0,"(57335, 62221)",0,1,0.5,10,8,0.777778,0.708333
76619,167592,2020/2021,2021-03-06,Big Ten Championships,149,Beau Bartlett,62221,Penn State,Yahya Thomas,49245,...,0,-2,"(49245, 62221)",0,0,0.5,11,8,0.800000,0.666667
76620,171776,2021/2022,2021-11-13,Sacred Heart - Penn State Dual,149,Beau Bartlett,62221,Penn State,Shaun Williams,51117,...,1,9,"(51117, 62221)",0,1,0.5,12,9,0.727273,0.076923
76621,171777,2021/2022,2021-11-13,Oregon State - Penn State Dual,149,Beau Bartlett,62221,Penn State,Cory Crooks,45179,...,1,1,"(45179, 62221)",0,1,0.5,13,10,0.750000,0.480000
76622,174117,2021/2022,2021-11-18,Army - Penn State Dual,149,Beau Bartlett,62221,Penn State,Pj Ogunsanya,54496,...,1,2,"(54496, 62221)",0,1,0.5,14,11,0.769231,0.710526
76623,177755,2021/2022,2021-12-03,Penn State - Pennsylvania Dual,149,Beau Bartlett,62221,Penn State,Anthony Artalona,51039,...,1,1,"(51039, 62221)",0,1,0.5,15,12,0.785714,0.555556

In [27]:
def calculate_avg_point_differential_last_5(df):
    df = df.sort_values(['wrestler_id', 'date'])
    
    # Calculate rolling average point differential
    df['avg_point_differential_last_5'] = df.groupby('wrestler_id')['point_differential'].rolling(
        window=5, min_periods=1
    ).mean().reset_index(0, drop=True)
    
    # Shift to avoid data leakage
    df['avg_point_differential_last_5'] = df.groupby('wrestler_id')['avg_point_differential_last_5'].shift(1)
    
    return df
test2 = calculate_avg_point_differential_last_5(test2)
test2[(test2['wrestler'] == 'Beau Bartlett')].head(15)

,index,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,...,point_differential,h2h_key,h2h_matches,h2h_wins,h2h_win_rate,matches_wrestled,cumulative_wins,career_win_rate,opponent_career_win_rate,avg_point_differential_last_5
76609,164603,2020/2021,2021-01-30,Indiana Penn State Extra,141,Beau Bartlett,62221,Penn State,Jacob Moran,63550,...,0,"(62221, 63550)",0,1,0.5,1,1,NaN,1.000000,NaN
76610,164610,2020/2021,2021-01-30,Penn State Northwestern Extra,141,Beau Bartlett,62221,Penn State,Colin Valdiviez,49244,...,4,"(49244, 62221)",0,1,0.5,2,2,1.000000,0.666667,0.000000
76611,164611,2020/2021,2021-01-30,Penn State Northwestern Extra,141,Beau Bartlett,62221,Penn State,Justin Benjamin,61997,...,6,"(61997, 62221)",0,1,0.5,3,3,1.000000,0.375000,2.000000
76612,165191,2020/2021,2021-02-02,Penn State Wisconsin Extra,141,Beau Bartlett,62221,Penn State,Dominic Dentino,56924,...,7,"(56924, 62221)",0,1,0.5,4,4,1.000000,0.153846,3.333333
76613,166398,2020/2021,2021-02-14,Michigan Penn State Extra,149,Beau Bartlett,62221,Penn State,Cole Mattin,57715,...,4,"(57715, 62221)",0,1,0.5,5,5,1.000000,0.500000,4.250000
76614,166536,2020/2021,2021-02-19,Penn State - Ohio State Dual,149,Beau Bartlett,62221,Penn State,Sammy Sasso,51143,...,-2,"(51143, 62221)",0,0,0.5,6,5,1.000000,0.920000,4.200000
76615,166673,2020/2021,2021-02-21,Maryland - Penn State Dual,149,Beau Bartlett,62221,Penn State,Hunter Baxter,49172,...,6,"(49172, 62221)",0,1,0.5,7,6,0.833333,0.115385,3.800000
76616,166674,2020/2021,2021-02-21,Penn State Maryland Extra,149,Beau Bartlett,62221,Penn State,Lucas Cordio,57120,...,8,"(57120, 62221)",0,1,0.5,8,7,0.857143,0.421053,4.200000
76617,167598,2020/2021,2021-03-06,Big Ten Championships,149,Beau Bartlett,62221,Penn State,Michael Blockhus,57163,...,-2,"(57163, 62221)",0,0,0.5,9,7,0.875000,0.628571,4.600000
76618,167576,2020/2021,2021-03-06,Big Ten Championships,149,Beau Bartlett,62221,Penn State,Michael North,57335,...,0,"(57335, 62221)",0,1,0.5,10,8,0.777778,0.708333,2.800000
76619,167592,2020/2021,2021-03-06,Big Ten Championships,149,Beau Bartlett,62221,Penn State,Yahya Thomas,49245,...,-2,"(49245, 62221)",0,0,0.5,11,8,0.800000,0.666667,2.000000
76620,171776,2021/2022,2021-11-13,Sacred Heart - Penn State Dual,149,Beau Bartlett,62221,Penn State,Shaun Williams,51117,...,9,"(51117, 62221)",0,1,0.5,12,9,0.727273,0.076923,2.000000
76621,171777,2021/2022,2021-11-13,Oregon State - Penn State Dual,149,Beau Bartlett,62221,Penn State,Cory Crooks,45179,...,1,"(45179, 62221)",0,1,0.5,13,10,0.750000,0.480000,2.600000
76622,174117,2021/2022,2021-11-18,Army - Penn State Dual,149,Beau Bartlett,62221,Penn State,Pj Ogunsanya,54496,...,2,"(54496, 62221)",0,1,0.5,14,11,0.769231,0.710526,1.200000
76623,177755,2021/2022,2021-12-03,Penn State - Pennsylvania Dual,149,Beau Bartlett,62221,Penn State,Anthony Artalona,51039,...,1,"(51039, 62221)",0,1,0.5,15,12,0.785714,0.555556,2.000000

In [28]:
def calculate_experience_differential(df):
    df = df.sort_values(['wrestler_id', 'date'])
    
    # Shift to get experience before current match
    df['experience'] = df.groupby('wrestler_id')['matches_wrestled'].shift(1).fillna(0)
    
    # Map opponent experience
    exp_mapping = df.groupby(['wrestler_id', 'date'])['experience'].first().reset_index()
    
    df = df.merge(
        exp_mapping.rename(columns={'wrestler_id': 'opponent_id', 'experience': 'opponent_experience'}),
        on=['opponent_id', 'date'],
        how='left'
    )
    
    # Calculate experience differential
    df['experience_differential'] = df['experience'] - df['opponent_experience']
    
    return df
test2 = calculate_experience_differential(test2)
test2[(test2['wrestler'] == 'Beau Bartlett')].tail(15)

,index,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,...,h2h_wins,h2h_win_rate,matches_wrestled,cumulative_wins,career_win_rate,opponent_career_win_rate,avg_point_differential_last_5,experience,opponent_experience,experience_differential
76713,258513,2024/2025,2025-02-07,Michigan - Penn State Dual,141,Beau Bartlett,62221,Penn State,Sergio Lemley,78641,...,3,1.000000,105,87,0.826923,0.680851,6.0,104.0,47.0,57.0
76714,259035,2024/2025,2025-02-09,Maryland - Penn State Dual,141,Beau Bartlett,62221,Penn State,Dario Lemus,78721,...,1,0.500000,106,88,0.828571,0.589744,3.8,105.0,39.0,66.0
76715,259510,2024/2025,2025-02-14,Penn State - Ohio State Dual,141,Beau Bartlett,62221,Penn State,Jesse Mendez,74054,...,2,0.333333,107,89,0.830189,0.865854,4.8,106.0,82.0,24.0
76716,259866,2024/2025,2025-02-16,Penn State - Illinois Dual,141,Beau Bartlett,62221,Penn State,Danny Pucino,66101,...,1,0.500000,108,90,0.831776,0.650602,5.0,107.0,83.0,24.0
76717,260503,2024/2025,2025-02-21,American - Penn State Dual,141,Beau Bartlett,62221,Penn State,Elijah White,69903,...,1,0.500000,109,91,0.833333,0.225000,5.6,108.0,40.0,68.0
76718,262157,2024/2025,2025-03-08,Big Ten Championships,141,Beau Bartlett,62221,Penn State,Jesse Mendez,74054,...,3,0.500000,110,92,0.834862,0.855422,8.0,109.0,83.0,26.0
76719,262158,2024/2025,2025-03-08,Big Ten Championships,141,Beau Bartlett,62221,Penn State,Greyson Clark,79389,...,1,0.500000,111,93,0.836364,0.590909,8.2,110.0,44.0,66.0
76720,262159,2024/2025,2025-03-08,Big Ten Championships,141,Beau Bartlett,62221,Penn State,Vance Vombaur,68715,...,1,1.000000,112,93,0.837838,0.746835,7.4,111.0,79.0,32.0
76721,262143,2024/2025,2025-03-08,Big Ten Championships,141,Beau Bartlett,62221,Penn State,Joey Olivieri,67238,...,3,1.000000,113,94,0.830357,0.695122,6.6,112.0,82.0,30.0
76722,262947,2024/2025,2025-03-20,NCAA Championships,141,Beau Bartlett,62221,Penn State,Jesse Mendez,74054,...,3,0.600000,114,94,0.831858,0.839080,5.6,113.0,87.0,26.0
76723,262948,2024/2025,2025-03-20,NCAA Championships,141,Beau Bartlett,62221,Penn State,Jordan Titus,68738,...,1,0.500000,115,95,0.824561,0.663793,2.2,114.0,116.0,-2.0
76724,262910,2024/2025,2025-03-20,NCAA Championships,141,Beau Bartlett,62221,Penn State,CJ Composto,62430,...,1,0.500000,116,96,0.826087,0.775281,2.2,115.0,89.0,26.0
76725,262914,2024/2025,2025-03-20,NCAA Championships,141,Beau Bartlett,62221,Penn State,CJ Composto,62430,...,2,1.000000,117,97,0.827586,0.775281,2.0,116.0,89.0,27.0
76726,262938,2024/2025,2025-03-20,NCAA Championships,141,Beau Bartlett,62221,Penn State,Julian Tagg,58261,...,1,0.500000,118,98,0.829060,0.566667,3.4,117.0,30.0,87.0
76727,262940,2024/2025,2025-03-20,NCAA Championships,141,Beau Bartlett,62221,Penn State,Joshua Koderhandt,70917,...,1,0.500000,119,99,0.830508,0.757576,3.6,118.0,132.0,-14.0

In [29]:
def calculate_scoring_advantage_5(df):
    df = df.sort_values(['wrestler_id', 'date'])
    
    # Calculate league average points scored by date
    df['league_avg_points'] = df.groupby('date')['wrestler_score'].transform('mean')
    
    # Calculate rolling average points scored
    df['avg_points_scored_5'] = df.groupby('wrestler_id')['wrestler_score'].rolling(
        window=5, min_periods=1
    ).mean().reset_index(0, drop=True)
    
    # Shift to avoid data leakage
    df['avg_points_scored_5'] = df.groupby('wrestler_id')['avg_points_scored_5'].shift(1)
    
    # Calculate scoring advantage
    df['scoring_advantage_5'] = df['avg_points_scored_5'] - df['league_avg_points']
    
    return df

def calculate_defensive_advantage_5(df):
    df = df.sort_values(['wrestler_id', 'date'])
    
    # Calculate league average points allowed by date
    df['league_avg_points_allowed'] = df.groupby('date')['opponent_score'].transform('mean')
    
    # Calculate rolling average points allowed
    df['avg_points_allowed_5'] = df.groupby('wrestler_id')['opponent_score'].rolling(
        window=5, min_periods=1
    ).mean().reset_index(0, drop=True)
    
    # Shift to avoid data leakage
    df['avg_points_allowed_5'] = df.groupby('wrestler_id')['avg_points_allowed_5'].shift(1)
    
    # Calculate defensive advantage (lower points allowed = better defense)
    df['defensive_advantage_5'] = df['league_avg_points_allowed'] - df['avg_points_allowed_5']
    
    return df

In [30]:
test2 = calculate_scoring_advantage_5(test2)
test2 = calculate_defensive_advantage_5(test2)
test2

,index,season,date,event,weight_class,wrestler,wrestler_id,wrestler_school,opponent,opponent_id,...,avg_point_differential_last_5,experience,opponent_experience,experience_differential,league_avg_points,avg_points_scored_5,scoring_advantage_5,league_avg_points_allowed,avg_points_allowed_5,defensive_advantage_5
0,169714,2021/2022,2021-11-06,Purdue - Drexel Dual,285,Michael Woulfe,12693,Purdue,Liam Dietrich,72622,...,NaN,0.0,0.0,0.0,4.398544,NaN,NaN,4.398544,NaN,NaN
1,169709,2021/2022,2021-11-06,Purdue - Rider Dual,285,Michael Woulfe,12693,Purdue,David Szuba,72908,...,0.000000,1.0,0.0,1.0,4.398544,0.000000,-4.398544,4.398544,0.000000,4.398544
2,174031,2021/2022,2021-11-14,Purdue - Cleveland State Dual,285,Michael Woulfe,12693,Purdue,John Kelbly,50329,...,0.000000,2.0,29.0,-27.0,4.502218,0.000000,-4.502218,4.502218,0.000000,4.502218
3,176820,2021/2022,2021-11-21,Northern Illinois - Purdue Dual,285,Michael Woulfe,12693,Purdue,Terrese Aaron,51827,...,0.000000,3.0,9.0,-6.0,4.774332,0.000000,-4.774332,4.774332,0.000000,4.774332
4,176799,2021/2022,2021-11-21,Brown - Purdue Dual,285,Michael Woulfe,12693,Purdue,Lear Quinton,62572,...,0.750000,4.0,3.0,1.0,4.774332,1.500000,-3.274332,4.774332,0.750000,4.024332
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222939,261388,2024/2025,2025-03-02,Zingo Nationals,197,Tommy Renna,101228,Unattached,Kevin Taylor,93979,...,-10.000000,1.0,25.0,-24.0,5.082011,0.000000,-5.082011,5.082011,10.000000,-4.917989
222940,196174,2022/2023,2022-11-13,Jonathan Kaloust Bearcat Open,197,Jude Correa,101285,High School,Lucas Cochran,71705,...,NaN,0.0,14.0,-14.0,4.513514,NaN,NaN,4.513514,NaN,NaN
222941,196176,2022/2023,2022-11-13,Jonathan Kaloust Bearcat Open,197,Jude Correa,101285,High School,Levko Higgins,50870,...,-4.000000,1.0,13.0,-12.0,4.513514,1.000000,-3.513514,4.513514,5.000000,-0.486486
222942,196223,2022/2023,2022-11-13,Jonathan Kaloust Bearcat Open,197,Jude Correa,101285,High School,Franklin Cruz,72182,...,-2.000000,2.0,0.0,2.0,4.513514,0.500000,-4.013514,4.513514,2.500000,2.013514
222943,196225,2022/2023,2022-11-13,Jonathan Kaloust Bearcat Open,197,Jude Correa,101285,High School,Xavier Vasquez,49233,...,-1.333333,3.0,34.0,-31.0,4.513514,0.333333,-4.180180,4.513514,1.666667,2.846847

In [31]:
def calculate_form_differential_5(df):
    df = df.sort_values(['wrestler_id', 'date'])
    
    # Calculate form (win rate) for last 5 matches
    df['form_last_5'] = df.groupby('wrestler_id')['is_win'].rolling(
        window=5, min_periods=1
    ).mean().reset_index(0, drop=True)
    
    # Shift to avoid data leakage
    df['form_last_5'] = df.groupby('wrestler_id')['form_last_5'].shift(1)
    
    # Create opponent form mapping
    form_mapping = df.groupby(['wrestler_id', 'date'])['form_last_5'].first().reset_index()
    
    # Map opponent form
    df = df.merge(
        form_mapping.rename(columns={'wrestler_id': 'opponent_id', 'form_last_5': 'opponent_form_last_5'}),
        on=['opponent_id', 'date'],
        how='left'
    )
    
    # Calculate form differential
    df['form_differential_5'] = df['form_last_5'] - df['opponent_form_last_5']
    
    return df

def calculate_dominant_win_rate_last_5(df, dominant_threshold=8):
    df = df.sort_values(['wrestler_id', 'date'])
    
    # Define dominant wins (e.g., winning by 10+ points)
    df['dominant_win'] = ((df['is_win'] == 1) & 
                         (df['wrestler_score'] - df['opponent_score'] >= dominant_threshold)).astype(int)
    
    # Calculate rolling dominant win rate
    df['dominant_win_rate_last_5'] = df.groupby('wrestler_id')['dominant_win'].rolling(
        window=5, min_periods=1
    ).mean().reset_index(0, drop=True)
    
    # Shift to avoid data leakage
    df['dominant_win_rate_last_5'] = df.groupby('wrestler_id')['dominant_win_rate_last_5'].shift(1)
    
    return df

def engineer_all_features(df):
    print("Engineering features...")
    
    # Apply all feature engineering functions
    df = calculate_win_rate_last_5(df)
    df = calculate_opponent_career_win_rate(df)
    df = calculate_form_differential_5(df)
    df = calculate_avg_point_differential_last_5(df)
    df = calculate_h2h_win_rate(df)
    df = calculate_experience_differential(df)
    df = calculate_scoring_advantage_5(df)
    df = calculate_defensive_advantage_5(df)
    df = calculate_dominant_win_rate_last_5(df)
    
    return df

In [32]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

In [33]:
def prepare_data_for_modeling(df):
    """Prepare data for logistic regression modeling"""
    priority_features = [
        'win_rate_last_5',
        'opponent_career_win_rate', 
        'form_differential_5',
        'avg_point_differential_last_5',
        'h2h_win_rate',
        'experience_differential',
        'scoring_advantage_5',
        'defensive_advantage_5',
        'dominant_win_rate_last_5'
    ]
    
    # Remove rows with NaN values in priority features
    df_clean = df.dropna(subset=priority_features + ['is_win'])
    
    # Separate features and target, keep date column
    X = df_clean[priority_features + ['date']]
    y = df_clean['is_win']
    
    return X, y, priority_features

In [34]:
def temporal_train_test_split(X, y, test_size=0.2, split_date=None):
    """Split data based on time to avoid data leakage"""
    
    if split_date is None:
        # Calculate split date based on test_size
        sorted_dates = X['date'].sort_values()
        split_idx = int(len(sorted_dates) * (1 - test_size))
        split_date = sorted_dates.iloc[split_idx]
    
    # Create temporal split
    train_mask = X['date'] < split_date
    test_mask = X['date'] >= split_date
    
    X_train = X[train_mask]
    X_test = X[test_mask]
    y_train = y[train_mask]
    y_test = y[test_mask]
    
    print(f"Split date: {split_date}")
    print(f"Train set: {len(X_train)} matches ({X_train['date'].min()} to {X_train['date'].max()})")
    print(f"Test set: {len(X_test)} matches ({X_test['date'].min()} to {X_test['date'].max()})")
    
    return X_train, X_test, y_train, y_test, split_date

def scale_features(X_train, X_test, feature_columns):
    """Scale features using training data statistics"""
    
    # Separate features from date
    X_train_features = X_train[feature_columns]
    X_test_features = X_test[feature_columns]
    
    # Scale features
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train_features)
    X_test_scaled = scaler.transform(X_test_features)
    
    # Convert back to DataFrame
    X_train_scaled = pd.DataFrame(X_train_scaled, columns=feature_columns, index=X_train.index)
    X_test_scaled = pd.DataFrame(X_test_scaled, columns=feature_columns, index=X_test.index)
    
    # Add back the date column
    X_train_scaled['date'] = X_train['date']
    X_test_scaled['date'] = X_test['date']
    
    return X_train_scaled, X_test_scaled, scaler

In [37]:
def train_logistic_regression(X, y, feature_columns):
    """Train logistic regression model with temporal split"""
    
    # Temporal split
    X_train, X_test, y_train, y_test, split_date = temporal_train_test_split(X, y)
    
    # Scale features
    X_train_scaled, X_test_scaled, scaler = scale_features(X_train, X_test, feature_columns)
    
    # Train model (only on feature columns, not date)
    model = LogisticRegression(random_state=42)
    model.fit(X_train_scaled[feature_columns], y_train)
    
    # Make predictions
    y_pred = model.predict(X_test_scaled[feature_columns])
    y_pred_proba = model.predict_proba(X_test_scaled[feature_columns])[:, 1]
    
    # Metrics
    train_acc = model.score(X_train_scaled[feature_columns], y_train)
    test_acc = model.score(X_test_scaled[feature_columns], y_test)
    auc_score = roc_auc_score(y_test, y_pred_proba)
    
    print(f"Train Accuracy: {train_acc:.4f}")
    print(f"Test Accuracy:  {test_acc:.4f}")
    print(f"ROC AUC Score:  {auc_score:.4f}")
    print(f"Overfitting:    {train_acc - test_acc:.4f}")
    
    # Classification report
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=['Loss', 'Win']))
    
    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)
    print(f"\nConfusion Matrix:")
    print(f"              Predicted")
    print(f"              Loss  Win")
    print(f"Actual Loss   {cm[0,0]:4d} {cm[0,1]:4d}")
    print(f"       Win    {cm[1,0]:4d} {cm[1,1]:4d}")
    
    feature_importance = pd.DataFrame({
        'feature': feature_columns,
        'coefficient': model.coef_[0],
        'abs_coefficient': np.abs(model.coef_[0])
    }).sort_values('abs_coefficient', ascending=False)
    
    print(feature_importance)
    
    return model, X_test_scaled, y_test, y_pred, y_pred_proba

In [38]:
df_engineered = engineer_all_features(raw).drop(columns=['index'])
X, y, feature_cols = prepare_data_for_modeling(df_engineered)
model, X_test, y_test, y_pred, y_pred_proba = train_logistic_regression(X, y, feature_cols)

Engineering features...
Split date: 2023-02-10
Train set: 364637 matches (2013-11-02 to 2023-02-09)
Test set: 91435 matches (2023-02-10 to 2025-03-20)
Train Accuracy: 0.7171
Test Accuracy:  0.7113
ROC AUC Score:  0.7822
Overfitting:    0.0059

Classification Report:
              precision    recall  f1-score   support

        Loss       0.71      0.72      0.71     45380
         Win       0.72      0.71      0.71     46055

    accuracy                           0.71     91435
   macro avg       0.71      0.71      0.71     91435
weighted avg       0.71      0.71      0.71     91435


Confusion Matrix:
              Predicted
              Loss  Win
Actual Loss   32464 12916
       Win    13485 32570
                         feature  coefficient  abs_coefficient
1       opponent_career_win_rate    -0.605804         0.605804
5        experience_differential     0.577544         0.577544
4                   h2h_win_rate     0.324570         0.324570
0                win_rate_last_5     0.210315         0.210315
2            form_differential_5     0.208970         0.208970
6            scoring_advantage_5     0.155642         0.155642
3  avg_point_differential_last_5     0.141762         0.141762
7          defensive_advantage_5     0.048574         0.048574
8       dominant_win_rate_last_5    -0.027150         0.027150